### ISSUE TITLE
Panic: Terraform resource names cannot start with a digit.

### ISSUE THREAD

**Issue by jtbonhomme** [kubernetes/kops#10360]
**1. What `kops` version are you running? 
`Version 1.18.2`

**2. What Kubernetes version are you running? `

`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
export KOPS_CLUSTER_NAME=dev.k8s.local
export KOPS_STATE_STORE=s3://izysaas.kops.states
export MASTER_COUNT="3"
export MASTER_VOLUME_SIZE="50"
export MASTER_INSTANCE_TYPE="t2.micro"
export MASTER_ZONES="eu-west-3a"
export NODE_COUNT="7"
export NODE_INSTANCE_TYPE="t2.micro"
export NODE_VOLUME_SIZE="20"
export NODE_ZONES="eu-west-3a,eu-west-3b,eu-west-3c"
export SSH_PUBLIC_KEY=kubernetes/secrets/k8s_rsa.pub

kops create cluster \
    --v 10 \
    --zones=${NODE_ZONES} \
    --name=${KOPS_CLUSTER_NAME} \
    --node-count=${NODE_COUNT} \
    --node-size=${NODE_INSTANCE_TYPE} \
    --node-volume-size=${NODE_VOLUME_SIZE} \
    --master-size=${MASTER_INSTANCE_TYPE} \
    --master-count=${MASTER_COUNT} \
    --master-volume-size=${MASTER_VOLUME_SIZE} \
    --master-zones=${MASTER_ZONES} \
    --ssh-public-key=${SSH_PUBLIC_KEY} \
    --authorization=alwaysAllow \
    --cloud=aws \
    --associate-public-ip=true --target=terraform --out=.
```

**5. What happened after the commands executed?**

```
I1203 14:12:57.642816   20110 create_cluster.go:1537] Using SSH public key: kubernetes/secrets/k8s_rsa.pub
I1203 14:12:57.644617   20110 factory.go:68] state store s3://izysaas.kops.states
I1203 14:12:57.646519   20110 s3context.go:340] GOOS="darwin", assuming not running on EC2
I1203 14:12:57.646587   20110 s3context.go:173] defaulting region to "us-east-1"
I1203 14:12:58.372542   20110 s3context.go:213] found bucket in region "eu-west-3"
I1203 14:12:58.373542   20110 s3fs.go:290] Reading file "s3://izysaas.kops.states/dev.k8s.local/config"
I1203 14:12:58.448361   20110 channel.go:97] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I1203 14:12:58.448435   20110 channel.go:102] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I1203 14:12:58.448746   20110 context.go:200] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I1203 14:12:58.670888   20110 channel.go:111] Channel contents: spec:

...

I1203 14:01:46.370028   13582 executor.go:103] Tasks: 96 done / 96 total; 0 can run
I1203 14:01:46.372501   13582 context.go:91] deleting temp dir: "/var/folders/dx/gj_hhpgj01zg_r9tvnl3yh100000gn/T/deploy249249245"
panic: Terraform resource names cannot start with a digit. This is a bug in Kops, please report this in a GitHub Issue. Name: 1.etcd-events.dev.k8s.local

goroutine 1 [running]:
k8s.io/kops/upup/pkg/fi/cloudup/terraform.tfSanitize(0xc000b3bcc0, 0x1b, 0x48a0e5e, 0xe)
	/private/tmp/kops-20201027-44494-1imc1oj/kops-1.18.2/src/k8s.io/kops/upup/pkg/fi/cloudup/terraform/target.go:104 +0x30c
k8s.io/kops/upup/pkg/fi/cloudup/terraform.(*TerraformTarget).finish012(0xc000aa6140, 0xc000bc2360, 0x0, 0x413a1a0)
	/private/tmp/kops-20201027-44494-1imc1oj/kops-1.18.2/src/k8s.io/kops/upup/pkg/fi/cloudup/terraform/target_0_12.go:61 +0x6d5
k8s.io/kops/upup/pkg/fi/cloudup/terraform.(*TerraformTarget).Finish(0xc000aa6140, 0xc000bc2360, 0xa, 0xc00058b201)
	/private/tmp/kops-20201027-44494-1imc1oj/kops-1.18.2/src/k8s.io/kops/upup/pkg/fi/cloudup/terraform/target.go:200 +0x545
k8s.io/kops/upup/pkg/fi/cloudup.(*ApplyClusterCmd).Run(0xc0003520f0, 0x4dd0360, 0xc000132010, 0x0, 0x0)
	/private/tmp/kops-20201027-44494-1imc1oj/kops-1.18.2/src/k8s.io/kops/upup/pkg/fi/cloudup/apply_cluster.go:938 +0x254f
main.RunUpdateCluster(0x4dd0360, 0xc000132010, 0xc0004212a0, 0x7ffeefbfe583, 0xd, 0x4d79f60, 0xc00012e008, 0xc000426ab0, 0x0, 0x0, ...)
	/private/tmp/kops-20201027-44494-1imc1oj/kops-1.18.2/src/k8s.io/kops/cmd/kops/update_cluster.go:274 +0x9dc
main.RunCreateCluster(0x4dd0360, 0xc000132010, 0xc0004212a0, 0x4d79f60, 0xc00012e008, 0xc0003d5c00, 0xc000147800, 0xc00055dd48)
	/private/tmp/kops-20201027-44494-1imc1oj/kops-1.18.2/src/k8s.io/kops/cmd/kops/create_cluster.go:1357 +0x3492
main.NewCmdCreateCluster.func1(0xc0002d3900, 0xc000279680, 0x0, 0x12)
	/private/tmp/kops-20201027-44494-1imc1oj/kops-1.18.2/src/k8s.io/kops/cmd/kops/create_cluster.go:274 +0x18d
github.com/spf13/cobra.(*Command).execute(0xc0002d3900, 0xc000279560, 0x12, 0x12, 0xc0002d3900, 0xc000279560)
	/private/tmp/kops-20201027-44494-1imc1oj/kops-1.18.2/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x67ba1e0, 0x680a3e0, 0x0, 0x0)
	/private/tmp/kops-20201027-44494-1imc1oj/kops-1.18.2/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/kops-20201027-44494-1imc1oj/kops-1.18.2/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.Execute()
	/private/tmp/kops-20201027-44494-1imc1oj/kops-1.18.2/src/k8s.io/kops/cmd/kops/root.go:96 +0x8f
main.main()
	/private/tmp/kops-20201027-44494-1imc1oj/kops-1.18.2/src/k8s.io/kops/cmd/kops/main.go:25 +0x25
```

**6. What did you expect to happen?**

I expected `kops` to generate terraform manifests.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-12-03T13:06:46Z"
  name: dev.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://izysaas.kops.states/dev.k8s.local
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-west-3a-1
      name: "1"
    - instanceGroup: master-eu-west-3a-2
      name: "2"
    - instanceGroup: master-eu-west-3a-3
      name: "3"
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-west-3a-1
      name: "1"
    - instanceGroup: master-eu-west-3a-2
      name: "2"
    - instanceGroup: master-eu-west-3a-3
      name: "3"
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.12
  masterPublicName: api.dev.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-3a
    type: Public
    zone: eu-west-3a
  - cidr: 172.20.64.0/19
    name: eu-west-3b
    type: Public
    zone: eu-west-3b
  - cidr: 172.20.96.0/19
    name: eu-west-3c
    type: Public
    zone: eu-west-3c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-12-03T13:06:46Z"
  labels:
    kops.k8s.io/cluster: dev.k8s.local
  name: master-eu-west-3a-1
spec:
  associatePublicIp: true
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201026
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-3a-1
  role: Master
  rootVolumeSize: 50
  subnets:
  - eu-west-3a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-12-03T13:06:46Z"
  labels:
    kops.k8s.io/cluster: dev.k8s.local
  name: master-eu-west-3a-2
spec:
  associatePublicIp: true
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201026
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-3a-2
  role: Master
  rootVolumeSize: 50
  subnets:
  - eu-west-3a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-12-03T13:06:46Z"
  labels:
    kops.k8s.io/cluster: dev.k8s.local
  name: master-eu-west-3a-3
spec:
  associatePublicIp: true
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201026
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-3a-3
  role: Master
  rootVolumeSize: 50
  subnets:
  - eu-west-3a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-12-03T13:06:46Z"
  labels:
    kops.k8s.io/cluster: dev.k8s.local
  name: nodes
spec:
  associatePublicIp: true
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201026
  machineType: t2.micro
  maxSize: 7
  minSize: 7
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-3a
  - eu-west-3b
  - eu-west-3c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Full log accessible here: https://izysaas-public.s3.eu-west-3.amazonaws.com/log-kops

**9. Anything else do we need to know?**

**Comment by jtbonhomme** [comment]
Duplicate of #9982, feel free to close
