### ISSUE TITLE
panic: runtime error on new or updated instance groups using mixedInstancesPolicy

### ISSUE THREAD

**Issue by nathanleyton** [kubernetes/kops#10837]
**1. What `kops` version are you running? The command `kops version`, will display
1.19.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.19.6

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops replace -f <file path> 

**5. What happened after the commands executed?**
new instance groups are not created and/or changes to machine types are not updated. 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2c451fa]

goroutine 1479 [running]:
k8s.io/kops/upup/pkg/fi/cloudup/awstasks.(*AutoscalingGroup).RenderAWS(0xc000dcd700, 0xc001484740, 0xc00095f000, 0xc000dcd700, 0xc00095f100, 0x0, 0x0)
        upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go:492 +0x1c9a
reflect.Value.call(0x3fefc00, 0xc000dcd700, 0x2a13, 0x412ea26, 0x4, 0xc00111be00, 0x4, 0x4, 0x4760f00, 0xc0010a9380, ...)
        GOROOT/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x3fefc00, 0xc000dcd700, 0x2a13, 0xc00111be00, 0x4, 0x4, 0xc000dcd700, 0x2a13, 0xc00111bda0)
        GOROOT/src/reflect/value.go:337 +0xb9
k8s.io/kops/upup/pkg/fi.(*Context).Render(0xc000a42aa0, 0x4691a00, 0xc00095f000, 0x4691a00, 0xc000dcd700, 0x4691a00, 0xc00095f100, 0x0, 0x0)
        upup/pkg/fi/context.go:222 +0xef5
k8s.io/kops/upup/pkg/fi.DefaultDeltaRunMethod(0x4691a00, 0xc000dcd700, 0xc000a42aa0, 0x476a180, 0xc000eec400)
        upup/pkg/fi/default_methods.go:79 +0x54a
k8s.io/kops/upup/pkg/fi/cloudup/awstasks.(*AutoscalingGroup).Run(0xc000dcd700, 0xc000a42aa0, 0xc001434010, 0x0)
        upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go:316 +0xd7
k8s.io/kops/upup/pkg/fi.(*executor).forkJoin.func1(0xc0011565a0, 0xf, 0xf, 0xc0013d2190, 0xc0008a0f20, 0xc00148caf0, 0xb)
        upup/pkg/fi/executor.go:187 +0x1ae
created by k8s.io/kops/upup/pkg/fi.(*executor).forkJoin
        upup/pkg/fi/executor.go:183 +0x105

**6. What did you expect to happen?**

the updates in my yaml to be applied as per usual. 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

No need to comment on this cluster being spot instances (including the masters), it is just a test cluster we bring up and down all the time anyway. It has worked until recently updating kops and only seems to be affected by changes to the instancegroups. 

```apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  generation: 11
  name: <redacted>
spec:
  additionalPolicies:
    master: |
      [{
          "Effect": "Allow",
          "Resource": [
            "<redacted>"
          ],
          "Action": "sts:AssumeRole"
      }]
    node: |
      [{
          "Effect": "Allow",
          "Resource": [
            "<redacted>"
          ],
          "Action": "sts:AssumeRole"
      }]
  api:
    loadBalancer:
      class: Classic
      crossZoneLoadBalancing: true
      type: Public
  authorization:
    rbac: {}
  channel: alpha
  cloudProvider: aws
  configBase: <redacted>
  dnsZone: <redacted>
  etcdClusters:
  - cpuRequest: "1"
    etcdMembers:
    - instanceGroup: master-eu-west-2a
      name: a
      volumeIops: 3000
      volumeSize: 20
      volumeThroughput: 125
      volumeType: gp3
    - instanceGroup: master-eu-west-2b
      name: b
      volumeIops: 3000
      volumeSize: 20
      volumeThroughput: 125
      volumeType: gp3
    - instanceGroup: master-eu-west-2c
      name: c
      volumeIops: 3000
      volumeSize: 20
      volumeThroughput: 125
      volumeType: gp3
    memoryRequest: 2G
    name: main
  - cpuRequest: 500m
    etcdMembers:
    - instanceGroup: master-eu-west-2a
      name: a
      volumeIops: 3000
      volumeSize: 20
      volumeThroughput: 125
      volumeType: gp3
    - instanceGroup: master-eu-west-2b
      name: b
      volumeIops: 3000
      volumeSize: 20
      volumeThroughput: 125
      volumeType: gp3
    - instanceGroup: master-eu-west-2c
      name: c
      volumeIops: 3000
      volumeSize: 20
      volumeThroughput: 125
      volumeType: gp3
    memoryRequest: 1G
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    featureGates:
      CSIBlockVolume: "true"
      CSIDriverRegistry: "true"
      CSIInlineVolume: "true"
      CSIMigration: "true"
      CSIMigrationAWS: "true"
      CSINodeInfo: "true"
      ExpandCSIVolumes: "true"
      VolumeSnapshotDataSource: "true"
  kubeControllerManager:
    enableProfiling: false
    experimentalClusterSigningDuration: 8760h0m0s
    horizontalPodAutoscalerCpuInitializationPeriod: 5m0s
    horizontalPodAutoscalerDownscaleDelay: 5m0s
    horizontalPodAutoscalerDownscaleStabilization: 5m0s
    horizontalPodAutoscalerInitialReadinessDelay: 30s
    horizontalPodAutoscalerSyncPeriod: 15s
    horizontalPodAutoscalerTolerance: 100m
    horizontalPodAutoscalerUpscaleDelay: 3m0s
  kubeDNS:
    nodeLocalDNS:
      cpuRequest: 50m
      enabled: true
      memoryRequest: 20Mi
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    enforceNodeAllocatable: pods,kube-reserved
    featureGates:
      CSIBlockVolume: "true"
      CSIDriverRegistry: "true"
      CSIInlineVolume: "true"
      CSIMigration: "true"
      CSIMigrationAWS: "true"
      CSINodeInfo: "true"
      ExpandCSIVolumes: "true"
    kubeReserved:
      cpu: "1"
      ephemeral-storage: 1Gi
      memory: 2Gi
    kubeReservedCgroup: /kube-reserved
    kubeletCgroups: /kube-reserved
    runtimeCgroups: /kube-reserved
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.6
  masterPublicName: <redacted>
  metricsServer:
    enabled: true
  networkCIDR: <redacted>
  networking:
    weave:
      mtu: 8912
  nodeTerminationHandler:
    enabled: true
  nonMasqueradeCIDR: <redacted>
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: k8s.stg.cluster
  subnets:
  - cidr: <redacted>
    name: eu-west-2a
    type: Private
    zone: eu-west-2a
  - cidr: <redacted>
    name: eu-west-2b
    type: Private
    zone: eu-west-2b
  - cidr: <redacted>
    name: eu-west-2c
    type: Private
    zone: eu-west-2c
  - cidr: <redacted>
    name: eu-west-2a-pub
    type: Public
    zone: eu-west-2a
  - cidr: <redacted>
    name: eu-west-2b-pub
    type: Public
    zone: eu-west-2b
  - cidr: <redacted>
    name: eu-west-2c-pub
    type: Public
    zone: eu-west-2c
  - cidr: <redacted>
    name: eu-west-2a-util
    type: Utility
    zone: eu-west-2a
  - cidr: <redacted>
    name: eu-west-2b-util
    type: Utility
    zone: eu-west-2b
  - cidr: <redacted>
    name: eu-west-2c-util
    type: Utility
    zone: eu-west-2c
  topology:
    bastion:
      bastionPublicName: <redacted>
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-16T05:24:38Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: <redacted>
  name: bastions
spec:
  associatePublicIp: true
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.micro
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t2.micro
    - t3.micro
    - t3a.micro
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
  nodeLabels:
    dest: bastions
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  rootVolumeIops: 3000
  rootVolumeSize: 16
  rootVolumeThroughput: 125
  rootVolumeType: gp3
  subnets:
  - eu-west-2a-util

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-16T05:24:30Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: <redacted>
  name: cass-nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.xlarge
  maxSize: 3
  minSize: 3
  mixedInstancesPolicy:
    instances:
    - t3a.xlarge
    - t2.xlarge
    - t3.xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
  nodeLabels:
    dest: cass
    kops.k8s.io/instancegroup: cass-nodes
  role: Node
  rootVolumeIops: 3000
  rootVolumeSize: 75
  rootVolumeThroughput: 125
  rootVolumeType: gp3
  subnets:
  - eu-west-2a
  - eu-west-2b
  - eu-west-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-16T05:24:28Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: <redacted>
  name: data-nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.xlarge
  maxSize: 6
  minSize: 6
  mixedInstancesPolicy:
    instances:
    - t3a.xlarge
    - t2.xlarge
    - t3.xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
  nodeLabels:
    dest: data
    kops.k8s.io/instancegroup: data-nodes
  role: Node
  rootVolumeIops: 3000
  rootVolumeSize: 75
  rootVolumeThroughput: 125
  rootVolumeType: gp3
  subnets:
  - eu-west-2a
  - eu-west-2b
  - eu-west-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-16T05:24:40Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: <redacted>
  name: freeswitch
spec:
  additionalSecurityGroups:
  - <redacted>
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.medium
  maxSize: 2
  minSize: 2
  mixedInstancesPolicy:
    instances:
    - t3a.medium
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
  nodeLabels:
    dest: freeswitch
    kops.k8s.io/instancegroup: freeswitch
  role: Node
  rootVolumeIops: 3000
  rootVolumeSize: 50
  rootVolumeThroughput: 125
  rootVolumeType: gp3
  subnets:
  - eu-west-2a
  - eu-west-2b
  - eu-west-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-16T05:24:31Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: <redacted>
  name: master-eu-west-2a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.xlarge
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3a.xlarge
    - t2.xlarge
    - t3.xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-2a
  role: Master
  rootVolumeIops: 3000
  rootVolumeSize: 75
  rootVolumeThroughput: 125
  rootVolumeType: gp3
  subnets:
  - eu-west-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-16T05:24:32Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: <redacted>
  name: master-eu-west-2b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.xlarge
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3a.xlarge
    - t2.xlarge
    - t3.xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-2a
  role: Master
  rootVolumeIops: 3000
  rootVolumeSize: 75
  rootVolumeThroughput: 125
  rootVolumeType: gp3
  subnets:
  - eu-west-2b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-16T05:24:34Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: <redacted>
  name: master-eu-west-2c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.xlarge
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3a.xlarge
    - t2.xlarge
    - t3.xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-2c
  role: Master
  rootVolumeIops: 3000
  rootVolumeSize: 75
  rootVolumeThroughput: 125
  rootVolumeType: gp3
  subnets:
  - eu-west-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-16T05:24:37Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: <redacted>
  name: mon-nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.2xlarge
  maxSize: 3
  minSize: 3
  mixedInstancesPolicy:
    instances:
    - t3a.2xlarge
    - t2.2xlarge
    - t3.2xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
  nodeLabels:
    dest: monitoring
    kops.k8s.io/instancegroup: mon-nodes
  role: Node
  rootVolumeIops: 3000
  rootVolumeSize: 75
  rootVolumeThroughput: 125
  rootVolumeType: gp3
  subnets:
  - eu-west-2a
  - eu-west-2b
  - eu-west-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-16T05:24:35Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: <redacted>
  name: nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.2xlarge
  maxSize: 8
  minSize: 8
  mixedInstancesPolicy:
    instances:
    - t3a.2xlarge
    - t2.2xlarge
    - t3.2xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
  nodeLabels:
    dest: apps
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeIops: 3000
  rootVolumeSize: 75
  rootVolumeThroughput: 125
  rootVolumeType: gp3
  subnets:
  - eu-west-2a
  - eu-west-2b
  - eu-west-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-16T05:24:39Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: <redacted>
  name: sbc
spec:
  additionalSecurityGroups:
  - <redacted>
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.medium
  maxSize: 2
  minSize: 2
  mixedInstancesPolicy:
    instances:
    - t3a.medium
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
  nodeLabels:
    dest: sbc
    kops.k8s.io/instancegroup: sbc
  role: Node
  rootVolumeIops: 3000
  rootVolumeSize: 50
  rootVolumeThroughput: 125
  rootVolumeType: gp3
  subnets:
  - eu-west-2a-pub
  - eu-west-2b-pub
  - eu-west-2c-pub

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

all relevant logs given above, 

**9. Anything else do we need to know?**

only point to note is that the new instance groups are there in the yaml but nothing is created in aws.

**Comment by hakman** [comment]
Looks identical to this one: https://github.com/kubernetes/kops/issues/10718

**Comment by nathanleyton** [comment]
> Looks identical to this one: #10718
> Can you take a look @nathanleyton?

Apologies, missed that one as I was only searching for open issues. Yes, it looks like the same issue. 

Cheers

**Comment by hakman** [comment]
1.19.1 should be out soon with the fix :)
