### ISSUE TITLE
Updating cluster failed after creating a new instance group ( GCP)

### ISSUE THREAD

**Issue by jkl373** [kubernetes/kops#13157]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
> kops version
I0129 12:18:15.462841   70239 featureflag.go:165] FeatureFlag "AlphaAllowGCE"=true
Version 1.21.4 (git-53e6bf3e5b0a77c78df2a7c60baca6e926fd5105)
```
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:46:22Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```
**3. What cloud provider are you using?**
GCP

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops create ig test-ig --subnet us-central1
kops update cluster --yes
```

**5. What happened after the commands executed?**
```
> kops update cluster --yes
I0129 12:20:54.015419   70263 featureflag.go:165] FeatureFlag "AlphaAllowGCE"=true
Using cluster from kubectl context: test-ig-creation.k8s.local


*********************************************************************************

A new kops version is available: 1.22.3
Upgrading is recommended
More information: https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_kops.md#1.22.3

*********************************************************************************

I0129 12:21:03.798614   70263 apply_cluster.go:483] Gossip DNS: skipping DNS validation
W0129 12:21:04.067595   70263 external_access.go:36] TODO: Harmonize gcemodel ExternalAccessModelBuilder with awsmodel
W0129 12:21:04.067824   70263 firewall.go:35] TODO: Harmonize gcemodel with awsmodel for firewall - GCE model is way too open
W0129 12:21:04.067840   70263 firewall.go:64] Adding overlay network for X -> node rule - HACK
W0129 12:21:04.067852   70263 firewall.go:118] Adding overlay network for X -> master rule - HACK
I0129 12:21:04.910840   70263 autoscalinggroup.go:153] VMs using Service Account: default
I0129 12:21:04.910893   70263 autoscalinggroup.go:161] gsa: default
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
k8s.io/kops/pkg/model/gcemodel.(*AutoscalingGroupModelBuilder).splitToZones(0xc000c46390, 0xc000e96700, 0xc000d8cc00, 0xc000d8cc00, 0x0)
	pkg/model/gcemodel/autoscalinggroup.go:209 +0x225
k8s.io/kops/pkg/model/gcemodel.(*AutoscalingGroupModelBuilder).Build(0xc000c46390, 0xc001073f60, 0x0, 0x0)
	pkg/model/gcemodel/autoscalinggroup.go:235 +0x54e
k8s.io/kops/upup/pkg/fi/cloudup.(*Loader).BuildTasks(0xc00170f860, 0xc000fa4000, 0xc000f63780, 0xc000a656e0, 0xc, 0xc0003d4000, 0x6)
	upup/pkg/fi/cloudup/loader.go:47 +0xc2
k8s.io/kops/upup/pkg/fi/cloudup.(*ApplyClusterCmd).Run(0xc00170fc38, 0x60a2990, 0xc0001a2020, 0x0, 0x0)
	upup/pkg/fi/cloudup/apply_cluster.go:667 +0x1b0a
main.RunUpdateCluster(0x60a2990, 0xc0001a2020, 0xc0009602e8, 0xc0007cb650, 0x22, 0x604d680, 0xc0001a4008, 0xc000692c80, 0x5, 0x57a6aa8, ...)
	cmd/kops/update_cluster.go:286 +0x695
main.NewCmdUpdateCluster.func1(0xc00017bb80, 0xc0007bb0b0, 0x0, 0x1)
	cmd/kops/update_cluster.go:113 +0x115
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc00017bb80, 0xc0007bb0a0, 0x1, 0x1, 0xc00017bb80, 0xc0007bb0a0)
	vendor/github.com/spf13/cobra/command.go:856 +0x2c2
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x8463ae0, 0x84b35d0, 0x0, 0x0)
	vendor/github.com/spf13/cobra/command.go:960 +0x375
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	vendor/github.com/spf13/cobra/command.go:897
main.Execute()
	cmd/kops/root.go:97 +0x8f
main.main()
	cmd/kops/main.go:24 +0x25
```

**6. What did you expect to happen?**
New IG should be created and nodes should be allocated.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
> kops get --name test-ig-creation.k8s.local -o yaml
I0129 12:22:50.043718   70270 featureflag.go:165] FeatureFlag "AlphaAllowGCE"=true
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-01-29T05:52:28Z"
  name: test-ig-creation.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    gceServiceAccount: default
  cloudProvider: gce
  configBase: gs://test-ig-creation-cluster/test-ig-creation.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-central1-a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-central1-a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.21.8
  masterPublicName: api.test-ig-creation.k8s.local
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: sre-sandbox-xxxx
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: us-central1
    region: us-central1
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-01-29T06:26:55Z"
  labels:
    kops.k8s.io/cluster: test-ig-creation.k8s.local
  name: test-ig
spec:
  image: ubuntu-os-cloud/ubuntu-2004-focal-v20211118
  machineType: n1-standard-2
  maxSize: 2
  minSize: 2
  nodeLabels:
    cloud.google.com/metadata-proxy-ready: "true"
    kops.k8s.io/instancegroup: test-ig
  role: Node
  subnets:
  - us-central1

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-01-29T05:52:30Z"
  labels:
    kops.k8s.io/cluster: test-ig-creation.k8s.local
  name: master-us-central1-a
spec:
  image: ubuntu-os-cloud/ubuntu-2004-focal-v20211118
  machineType: n1-standard-1
  maxSize: 1
  minSize: 1
  nodeLabels:
    cloud.google.com/metadata-proxy-ready: "true"
    kops.k8s.io/instancegroup: master-us-central1-a
  role: Master
  subnets:
  - us-central1
  zones:
  - us-central1-a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-01-29T05:52:31Z"
  labels:
    kops.k8s.io/cluster: test-ig-creation.k8s.local
  name: nodes-us-central1-a
spec:
  image: ubuntu-os-cloud/ubuntu-2004-focal-v20211118
  machineType: n1-standard-2
  maxSize: 1
  minSize: 1
  nodeLabels:
    cloud.google.com/metadata-proxy-ready: "true"
    kops.k8s.io/instancegroup: nodes-us-central1-a
  role: Node
  subnets:
  - us-central1
  zones:
  - us-central1-a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
nil

**Comment by jkl373** [comment]
Adding zone to new IG spec resolved the issue
