### ISSUE TITLE
🐛 Go Panic runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by pcgeek86** [kubernetes/kops#14337]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.25

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster --node-count=1 --name=trevor.cbttrevor.com --state=statefile --cloud=aws
```

**5. What happened after the commands executed?**

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
k8s.io/kops/upup/pkg/fi/cloudup.NewCluster(0xc00089e000, {0x5726f40, 0xc00095ef20})
        k8s.io/kops/upup/pkg/fi/cloudup/new_cluster.go:278 +0x2ae5
main.RunCreateCluster({0x5715b60, 0xc000052048}, 0x14?, {0x56ed900, 0xc00000a018}, 0xc00089e000)
        k8s.io/kops/cmd/kops/create_cluster.go:517 +0x33f
main.NewCmdCreateCluster.func1(0xc000955180?, {0xc00095a340?, 0x4?, 0x4?})
        k8s.io/kops/cmd/kops/create_cluster.go:205 +0x177
github.com/spf13/cobra.(*Command).execute(0xc000955180, {0xc00095a300, 0x4, 0x4})
        github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x79921a0)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
main.Execute()
        k8s.io/kops/cmd/kops/root.go:95 +0x5c
main.main()
        k8s.io/kops/cmd/kops/main.go:20 +0x17
```

**6. What did you expect to happen?**

Kops command creates a new cluster, or provides a helpful error message.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

n/a

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

```
I0926 07:33:01.324079   25976 factory.go:83] state store statefile
I0926 07:33:01.326318   25976 channel.go:123] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I0926 07:33:01.326318   25976 channel.go:143] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I0926 07:33:01.327935   25976 context.go:210] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I0926 07:33:01.588528   25976 channel.go:152] Channel contents: spec:
  images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.7.0 <1.8.0"
    - name: kope.io/k8s-1.8-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.8.0 <1.9.0"
    - name: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.9.0 <1.10.0"
    - name: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.10.0 <1.11.0"
    # Stretch is the default for 1.11 (for nvme)
    - name: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.11.0 <1.12.0"
    - name: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.12.0 <1.13.0"
    - name: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.13.0 <1.14.0"
    - name: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.14.0 <1.15.0"
    - name: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.15.0 <1.16.0"
    - name: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.16.0 <1.17.0"
    - name: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.17.0 <1.18.0"
    - name: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220810
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.18.0"
    - name: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20220810
      providerID: aws
      architectureID: arm64
      kubernetesVersion: ">=1.20.0"
    - name: cos-cloud/cos-stable-65-10323-99-0
      providerID: gce
      architectureID: amd64
      kubernetesVersion: "<1.16.0-alpha.1"
    - name: "cos-cloud/cos-stable-77-12371-114-0"
      providerID: gce
      architectureID: amd64
      kubernetesVersion: ">=1.16.0 <1.18.0"
    - name: ubuntu-os-cloud/ubuntu-2004-focal-v20220118
      providerID: gce
      architectureID: amd64
      kubernetesVersion: ">=1.18.0"
    - name: Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:20.04.202110010
      providerID: azure
      architectureID: amd64
      kubernetesVersion: ">=1.20.0"
  cluster:
    kubernetesVersion: v1.5.8
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.25.0"
    recommendedVersion: 1.25.2
    requiredVersion: 1.25.0
  - range: ">=1.24.0"
    recommendedVersion: 1.24.6
    requiredVersion: 1.24.0
  - range: ">=1.23.0"
    recommendedVersion: 1.23.12
    requiredVersion: 1.23.0
  - range: ">=1.22.0"
    recommendedVersion: 1.22.15
    requiredVersion: 1.22.0
  - range: ">=1.21.0"
    recommendedVersion: 1.21.14
    requiredVersion: 1.21.0
  - range: ">=1.20.0"
    recommendedVersion: 1.20.15
    requiredVersion: 1.20.0
  - range: ">=1.19.0"
    recommendedVersion: 1.19.16
    requiredVersion: 1.19.0
  - range: ">=1.18.0"
    recommendedVersion: 1.18.20
    requiredVersion: 1.18.0
  - range: ">=1.17.0"
    recommendedVersion: 1.17.17
    requiredVersion: 1.17.0
  - range: ">=1.16.0"
    recommendedVersion: 1.16.15
    requiredVersion: 1.16.0
  - range: ">=1.15.0"
    recommendedVersion: 1.15.12
    requiredVersion: 1.15.0
  - range: ">=1.14.0"
    recommendedVersion: 1.14.10
    requiredVersion: 1.14.0
  - range: ">=1.13.0"
    recommendedVersion: 1.13.12
    requiredVersion: 1.13.0
  - range: ">=1.12.0"
    recommendedVersion: 1.12.10
    requiredVersion: 1.12.0
  - range: ">=1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.0
  - range: "<1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.10
  kopsVersions:
  - range: ">=1.25.0-alpha.1"
    recommendedVersion: "1.25.0"
    #requiredVersion: 1.25.0
    kubernetesVersion: 1.25.2
  - range: ">=1.24.0-alpha.1"
    recommendedVersion: "1.24.3"
    #requiredVersion: 1.24.0
    kubernetesVersion: 1.24.6
  - range: ">=1.23.0-alpha.1"
    recommendedVersion: "1.24.3"
    #requiredVersion: 1.23.0
    kubernetesVersion: 1.23.12
  - range: ">=1.22.0-alpha.1"
    recommendedVersion: "1.24.3"
    #requiredVersion: 1.22.0
    kubernetesVersion: 1.22.15
  - range: ">=1.21.0-alpha.1"
    recommendedVersion: "1.24.3"
    #requiredVersion: 1.21.0
    kubernetesVersion: 1.21.14
  - range: ">=1.20.0-alpha.1"
    recommendedVersion: "1.24.3"
    #requiredVersion: 1.20.0
    kubernetesVersion: 1.20.15
  - range: ">=1.19.0-alpha.1"
    recommendedVersion: "1.24.3"
    #requiredVersion: 1.19.0
    kubernetesVersion: 1.19.16
  - range: ">=1.18.0-alpha.1"
    recommendedVersion: "1.23.4"
    #requiredVersion: 1.18.0
    kubernetesVersion: 1.18.20
  - range: ">=1.17.0-alpha.1"
    recommendedVersion: "1.22.3"
    #requiredVersion: 1.17.0
    kubernetesVersion: 1.17.17
  - range: ">=1.16.0-alpha.1"
    recommendedVersion: "1.21.4"
    #requiredVersion: 1.16.0
    kubernetesVersion: 1.16.15
  - range: ">=1.15.0-alpha.1"
    recommendedVersion: "1.21.4"
    #requiredVersion: 1.15.0
    kubernetesVersion: 1.15.12
  - range: ">=1.14.0-alpha.1"
    #recommendedVersion: "1.14.0"
    #requiredVersion: 1.14.0
    kubernetesVersion: 1.14.10
  - range: ">=1.13.0-alpha.1"
    #recommendedVersion: "1.13.0"
    #requiredVersion: 1.13.0
    kubernetesVersion: 1.13.12
  - range: ">=1.12.0-alpha.1"
    recommendedVersion: "1.12.1"
    #requiredVersion: 1.12.0
    kubernetesVersion: 1.12.10
  - range: ">=1.11.0-alpha.1"
    recommendedVersion: "1.11.1"
    #requiredVersion: 1.11.0
    kubernetesVersion: 1.11.10
  - range: "<1.11.0-alpha.1"
    recommendedVersion: "1.11.1"
    #requiredVersion: 1.10.0
    kubernetesVersion: 1.11.10
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
k8s.io/kops/upup/pkg/fi/cloudup.NewCluster(0xc000513b00, {0x5726f40, 0xc00046b9e0})
        k8s.io/kops/upup/pkg/fi/cloudup/new_cluster.go:278 +0x2ae5
main.RunCreateCluster({0x5715b60, 0xc000126018}, 0x14?, {0x56ed900, 0xc00014a008}, 0xc000513b00)
        k8s.io/kops/cmd/kops/create_cluster.go:517 +0x33f
main.NewCmdCreateCluster.func1(0xc000004280?, {0xc000338a00?, 0x5?, 0x5?})
        k8s.io/kops/cmd/kops/create_cluster.go:205 +0x177
github.com/spf13/cobra.(*Command).execute(0xc000004280, {0xc0003389b0, 0x5, 0x5})
        github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x79921a0)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
main.Execute()
        k8s.io/kops/cmd/kops/root.go:95 +0x5c
main.main()
        k8s.io/kops/cmd/kops/main.go:20 +0x17
```

**9. Anything else do we need to know?**

**Comment by pcgeek86** [comment]
Awesome, thanks for the quick fix!!
