### ISSUE TITLE
GCE private topology with bastion fails

### ISSUE THREAD

**Issue by codingkriggs** [kubernetes/kops#15590]
/kind bug

Note, I have used substitutes `<bucket>` and `<project>` to hide private information in this report.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Client version: 1.26.4 (git-v1.26.4)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**3. What cloud provider are you using?**

GCE

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`$ kops create cluster simple.k8s.local --zones us-west1-c --state gs://<bucket>/ --project=<project> --topology private --bastion=true --cloud gce`

**5. What happened after the commands executed?**

```
I0704 14:59:23.440409    2001 new_cluster.go:1354] Cloud Provider ID: "gce"
I0704 14:59:23.665178    2001 network.go:109] scanning regions for subnetwork CIDR allocations
I0704 14:59:23.769181    2001 network.go:238] assigned 10.0.32.0/20 to subnet us-west1
Previewing changes that will be made:

W0704 14:59:29.273167    2001 external_access.go:39] TODO: Harmonize gcemodel ExternalAccessModelBuilder with awsmodel
W0704 14:59:29.273221    2001 firewall.go:41] TODO: Harmonize gcemodel with awsmodel for firewall - GCE model is way too open
W0704 14:59:29.273331    2001 storageacl.go:165] adding bucket level write IAM for role "<bucket>" to gs://ControlPlane to support etcd backup
W0704 14:59:29.273450    2001 autoscalinggroup.go:130] enabling storage-rw for etcd backups
I0704 14:59:29.274669    2001 executor.go:111] Tasks: 0 done / 71 total; 46 can run
W0704 14:59:29.307527    2001 vfs_castore.go:383] CA private key was not found
I0704 14:59:29.441221    2001 executor.go:111] Tasks: 46 done / 71 total; 14 can run
I0704 14:59:29.601269    2001 executor.go:111] Tasks: 60 done / 71 total; 8 can run
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x21480c9]

goroutine 492 [running]:
k8s.io/kops/upup/pkg/fi.CopyResource({0x58e9e20, 0xc001521170}, {0x0?, 0x0?})
        k8s.io/kops/upup/pkg/fi/resources.go:85 +0x69
k8s.io/kops/upup/pkg/fi.ResourceAsString({0x0, 0x0})
        k8s.io/kops/upup/pkg/fi/resources.go:103 +0x4c
k8s.io/kops/upup/pkg/fi/cloudup/gcetasks.(*InstanceTemplate).mapToGCE(0xc000272780, {0x7ffeaf35b7af, 0xc}, {0xc000c35410, 0x8})
        k8s.io/kops/upup/pkg/fi/cloudup/gcetasks/instancetemplate.go:347 +0xb8a
k8s.io/kops/upup/pkg/fi/cloudup/gcetasks.(*InstanceTemplate).Find(0xc000272780, 0x2?)
        k8s.io/kops/upup/pkg/fi/cloudup/gcetasks/instancetemplate.go:103 +0x1e7
reflect.Value.call({0x4c25b00?, 0xc000272780?, 0x2?}, {0x4f127df, 0x4}, {0xc000919e30, 0x1, 0x593f748?})
        reflect/value.go:586 +0xb0b
reflect.Value.Call({0x4c25b00?, 0xc000272780?, 0x4f4eef2?}, {0xc000919e30?, 0xc00135bd20?, 0xc000f5bb00?})
        reflect/value.go:370 +0xbc
k8s.io/kops/util/pkg/reflectutils.InvokeMethod({0x4c25b00, 0xc000272780?}, {0x4f12877, 0x4}, {0xc001124dd0, 0x1, 0xc001124dd8?})
        k8s.io/kops/util/pkg/reflectutils/walk.go:78 +0x52c
k8s.io/kops/upup/pkg/fi.invokeFind[...]({0x58f2120, 0xc000272780?}, 0xc001124e30?)
        k8s.io/kops/upup/pkg/fi/default_methods.go:144 +0x8c
k8s.io/kops/upup/pkg/fi.defaultDeltaRunMethod[...]({0x58f2120, 0xc000272780?}, 0xc0010562d0)
        k8s.io/kops/upup/pkg/fi/default_methods.go:68 +0x155
k8s.io/kops/upup/pkg/fi.CloudupDefaultDeltaRunMethod(...)
        k8s.io/kops/upup/pkg/fi/default_methods.go:41
k8s.io/kops/upup/pkg/fi/cloudup/gcetasks.(*InstanceTemplate).Run(0xc00097a780?, 0x58f2120?)
        k8s.io/kops/upup/pkg/fi/cloudup/gcetasks/instancetemplate.go:233 +0x2d
k8s.io/kops/upup/pkg/fi.(*executor[...]).forkJoin.func1(0x0)
        k8s.io/kops/upup/pkg/fi/executor.go:195 +0x28d
created by k8s.io/kops/upup/pkg/fi.(*executor[...]).forkJoin
        k8s.io/kops/upup/pkg/fi/executor.go:183 +0x86
```

**6. What did you expect to happen?**

No failure. Script completion without errors, private topology created, bastion created.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
$ kops get --name simple.k8s.local -o yaml
W0704 15:00:14.834151    2018 get.go:78] `kops get [CLUSTER]` is deprecated: use `kops get all [CLUSTER]`
```

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2023-07-04T14:59:24Z"
  name: simple.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig: {}
  cloudProvider: gce
  configBase: gs://<bucket>/simple.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: control-plane-us-west1-c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: control-plane-us-west1-c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.26.6
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  project: <project>
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 10.0.32.0/20
    name: us-west1
    region: us-west1
    type: Private
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-07-04T14:59:25Z"
  labels:
    kops.k8s.io/cluster: simple.k8s.local
  name: bastions
spec:
  image: ubuntu-os-cloud/ubuntu-2004-focal-v20230302
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: e2-micro
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - us-west1
  zones:
  - us-west1-c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-07-04T14:59:24Z"
  labels:
    kops.k8s.io/cluster: simple.k8s.local
  name: control-plane-us-west1-c
spec:
  image: ubuntu-os-cloud/ubuntu-2004-focal-v20230302
  machineType: e2-medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-west1
  zones:
  - us-west1-c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-07-04T14:59:25Z"
  labels:
    kops.k8s.io/cluster: simple.k8s.local
  name: nodes-us-west1-c
spec:
  image: ubuntu-os-cloud/ubuntu-2004-focal-v20230302
  machineType: e2-medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    cloud.google.com/metadata-proxy-ready: "true"
  role: Node
  subnets:
  - us-west1
  zones:
  - us-west1-c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

(First I will delete the cluster, and then recreate it with the verbose flag.)

```
$ kops delete cluster simple.k8s.local --yes
I0704 15:01:34.675533    2050 delete_cluster.go:128] Looking for cloud resources to delete
I0704 15:01:34.855402    2050 gce.go:99] Scanning zones: [us-west1-b us-west1-c us-west1-a]
W0704 15:01:36.354851    2050 gce.go:904] skipping subnetwork "https://www.googleapis.com/compute/v1/projects/<project>/regions/us-west1/subnetworks/us-west1-simple-k8s-local" because it didn't match any instance template
W0704 15:01:36.694722    2050 gce.go:1179] skipping network "https://www.googleapis.com/compute/v1/projects/<project>/global/networks/simple-k8s-local" because it didn't match any instance template
No cloud resources to delete

Deleted cluster: "simple.k8s.local"
```

```
$ kops create cluster simple.k8s.local --zones us-west1-c --state gs://<bucket>/ --project=<project> --topology private --bastion=true --cloud gce -v 10
```

See gist for output of this command: https://gist.github.com/codingkriggs/c8e6876121753882b98ef940fb22e948

**9. Anything else do we need to know?**

**Comment by codingkriggs** [comment]
Confirmed: reported issue has been corrected in version 1.27.0
