### ISSUE TITLE
panic with validate

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1897]
First time I have seen this one

```
goroutine 1 [running]:
panic(0x15703e0, 0xc420a90870)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
reflect.Value.call(0x15e0360, 0x1ab2d48, 0x13, 0x1963ac2, 0x4, 0xc420609060, 0x1, 0x1, 0x2d0cc20, 0x0, ...)
	/usr/local/Cellar/go/1.7/libexec/src/reflect/value.go:371 +0x10c0
reflect.Value.Call(0x15e0360, 0x1ab2d48, 0x13, 0xc420609060, 0x1, 0x1, 0x0, 0x1, 0x0)
	/usr/local/Cellar/go/1.7/libexec/src/reflect/value.go:302 +0xa4
k8s.io/kops/util/pkg/tables.(*TableColumn).getFromValue(0xc420a8be30, 0x15703e0, 0xc42043dc00, 0x198, 0x15703e0, 0xc42043dc00)
	/Users/clove/Workspace/src/k8s.io/kops/util/pkg/tables/format.go:43 +0xd7
k8s.io/kops/util/pkg/tables.(*Table).Render(0xc420cd9620, 0x154b980, 0xc420609040, 0x2643b00, 0xc420030010, 0xc420cd9650, 0x1, 0x1, 0x0, 0x0)
	/Users/clove/Workspace/src/k8s.io/kops/util/pkg/tables/format.go:116 +0x274
main.RunValidateCluster(0xc420410080, 0xc42041a240, 0x273fbe0, 0x0, 0x0, 0x2643b00, 0xc420030010, 0x273fbe0, 0x1, 0xc4200a2150)
	/Users/clove/Workspace/src/k8s.io/kops/cmd/kops/validate_cluster.go:179 +0x1651
main.NewCmdValidateCluster.func1(0xc42041a240, 0x273fbe0, 0x0, 0x0)
	/Users/clove/Workspace/src/k8s.io/kops/cmd/kops/validate_cluster.go:50 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc42041a240, 0x273fbe0, 0x0, 0x0, 0xc42041a240, 0x273fbe0)
	/Users/clove/Workspace/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2713d00, 0x1588300, 0x0, 0x0)
	/Users/clove/Workspace/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x2713d00, 0x273fbe0, 0x0)
	/Users/clove/Workspace/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
	/Users/clove/Workspace/src/k8s.io/kops/cmd/kops/root.go:70 +0x9d
main.main()
	/Users/clove/Workspace/src/k8s.io/kops/cmd/kops/main.go:25 +0x14
```

**Comment by justinsb** [comment]
Your use of the table rendering is wrong.  Will send a fix.
