### ISSUE TITLE
Log nicer error when attempting to run kops command on a cluster not managed by kops

### ISSUE THREAD

**Issue by tanner-bruce** [kubernetes/kops#2099]
We have a couple older clusters not created with kops. When I tried to run `kops create ig ...` with one those clusters as the current context in my kubecfg, I received this error.

```
Using cluster from kubectl context: main

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0x4dda42]

goroutine 1 [running]:
panic(0x1db4100, 0xc4200120c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kops/upup/pkg/fi/cloudup.ChannelForCluster(0x0, 0x2f48180, 0xc4204a52d0, 0x0)
	/go/src/k8s.io/kops/upup/pkg/fi/cloudup/apply_cluster.go:875 +0x22
main.RunCreateInstanceGroup(0xc4202993c0, 0xc4202c7200, 0xc4204a4870, 0x1, 0x1, 0x2f3eb80, 0xc42002e010, 0xc4204a4520, 0x0, 0x0)
	/go/src/k8s.io/kops/cmd/kops/create_ig.go:82 +0x171
main.NewCmdCreateInstanceGroup.func1(0xc4202c7200, 0xc4204a4870, 0x1, 0x1)
	/go/src/k8s.io/kops/cmd/kops/create_ig.go:48 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202c7200, 0xc4204a4800, 0x1, 0x1, 0xc4202c7200, 0xc4204a4800)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3013400, 0x1c4fc00, 0x0, 0x0)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x3013400, 0x3040c68, 0x0)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
	/go/src/k8s.io/kops/cmd/kops/root.go:70 +0x9d
main.main()
	/go/src/k8s.io/kops/cmd/kops/main.go:25 +0x14```

**Comment by kris-nova** [comment]
@tanner-bruce 

Looks like there was a patch for this. Do you mind re-trying this again in the next release to see if you can replicate?

**Comment by chrislovecnm** [comment]
Bump, can we close?
