### ISSUE TITLE
GCE rolling-update cluster not working.

### ISSUE THREAD

**Issue by Dirbaio** [kubernetes/kops#2115]
When I run rolling-update I get this panic. From a brief look over the code it seems rolling-update still assumes the only cloud is AWS.

````
dirbaio@neptune:~$ kops rolling-update cluster c1.alpha.verse.lol
ERROR: logging before flag.Parse: I0313 21:38:29.789354   13185 featureflag.go:90] FeatureFlag "AlphaAllowGCE"=true
panic: interface conversion: *gce.GCECloud is not awsup.AWSCloud: missing method AddAWSTags

goroutine 1 [running]:
k8s.io/kops/upup/pkg/kutil.FindCloudInstanceGroups(0x31e5580, 0xc42030ef00, 0xc42092d500, 0xc42047d5b0, 0x2, 0x2, 0x1, 0xc4201f2a80, 0x3, 0x4, ...)
	/home/dirbaio/go/src/k8s.io/kops/upup/pkg/kutil/rollingupdate_cluster.go:64 +0x5c
main.RunRollingUpdateCluster(0xc4202c4da0, 0x31dbdc0, 0xc42000e018, 0xc42008f860, 0x0, 0x0)
	/home/dirbaio/go/src/k8s.io/kops/cmd/kops/rollingupdatecluster.go:230 +0x9ba
main.NewCmdRollingUpdateCluster.func1(0xc420172240, 0xc4203f1f40, 0x1, 0x1)
	/home/dirbaio/go/src/k8s.io/kops/cmd/kops/rollingupdatecluster.go:138 +0xdd
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc420172240, 0xc4203f1f00, 0x1, 0x1, 0xc420172240, 0xc4203f1f00)
	/home/dirbaio/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x31ca0a0, 0x1ca5d00, 0x0, 0x0)
	/home/dirbaio/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x31ca0a0, 0x32d8d18, 0x0)
	/home/dirbaio/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
	/home/dirbaio/go/src/k8s.io/kops/cmd/kops/root.go:70 +0x9b
main.main()
	/home/dirbaio/go/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
````

**Comment by chrislovecnm** [comment]
This is a known limitation :)

**Comment by mstump** [comment]
+1

**Comment by Nowaker** [comment]
From https://github.com/kubernetes/kops/pull/3112:

> In order to support rolling updates, the first step was to refactor GCECloud into an interface, in order to match AWS implementation.

Now that https://github.com/kubernetes/kops/pull/3292 ("Implementing GCE as an interface") is done, how are we looking with rolling updates for GCE, @chrislovecnm? Super eager to see it working one day. :smiley: Thanks for all the work.

**Comment by chrislovecnm** [comment]
Work in progress when I have time

**Comment by negz** [comment]
I'm guessing this is the same bug, given the stack, but wanted to be explicit that this happens on `delete instancegroup` too.

```
$ kops version
Version 1.7.1

$ kops delete instancegroups --name experimental.gcp.k8s.local nodes
Do you really want to delete instance group "nodes"? This action cannot be undone. (y/N)                                                                               
y                                        
InstanceGroup "nodes" found for deletion 
panic: interface conversion: *gce.GCECloud is not awsup.AWSCloud: missing method AddAWSTags                                                                            

goroutine 1 [running]:                   
k8s.io/kops/pkg/instancegroups.FindCloudInstanceGroups(0x5a10ae0, 0xc420425f00, 0xc420a72a80, 0xc42079fa70, 0x1, 0x1, 0x10cad00, 0x0, 0x0, 0x0, ...)                   
        /private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/pkg/instancegroups/instancegroups.go:42 +0x5c                                               
k8s.io/kops/pkg/instancegroups.(*DeleteInstanceGroup).DeleteInstanceGroup(0xc42079fc00, 0xc42053eb40, 0x3f7a520, 0x24)                                                 
        /private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/pkg/instancegroups/instancegroups.go:105 +0xa7                                              
main.RunDeleteInstanceGroup(0xc42023f000, 0x5a05ce0, 0xc42000e018, 0xc420691500, 0x1, 0xc42076bf80)                                                                    
        /private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/cmd/kops/delete_instancegroup.go:158 +0x447                                                 
main.NewCmdDeleteInstanceGroup.func1(0xc4201ead80, 0xc420691bf0, 0x1, 0x3)         
        /private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/cmd/kops/delete_instancegroup.go:100 +0x12e                                                 
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc4201ead80, 0xc420691b60, 0x3, 0x3, 0xc4201ead80, 0xc420691b60)                                         
        /private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x234                                         
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5b953c0, 0x37d1f00, 0x0, 0x0)                                                                          
        /private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x2fe                                         
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x5b953c0, 0x5bc9980, 0x0)                                                                                
        /private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b                                          
main.Execute()                           
        /private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/cmd/kops/root.go:98 +0x91                                                                   
main.main()                              
        /private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/cmd/kops/main.go:25 +0x20 
```

**Comment by chrislovecnm** [comment]
Again not implemented in kops 1.7.x please try kops 1.8.x or master with all versions of k8s

**Comment by chrislovecnm** [comment]
Closing as this is in the alpha 1.8.1 release

**Comment by chrislovecnm** [comment]
Sorry 1.8.0 alpha release

**Comment by Nowaker** [comment]
Good job, @chrislovecnm! Thank you.
