### ISSUE TITLE
kops panic creating third master IG in us-west-1

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#2154]
```
$ kops create ig master-us-west-1a-2 --role=Master
Using cluster from kubectl context: dev-us-east-1c.dev.kuber.example.com

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0xde9d2]

goroutine 1 [running]:
panic(0x19bebe0, 0xc420012190)
	/Users/jprice/programs/git/homebrew/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
k8s.io/kops/upup/pkg/fi/cloudup.ChannelForCluster(0x0, 0x2b695e0, 0xc420012630, 0x0)
	/Users/jprice/programs/gopath/src/k8s.io/kops/upup/pkg/fi/cloudup/apply_cluster.go:875 +0x22
main.RunCreateInstanceGroup(0xc420458d00, 0xc420429b00, 0xc420459500, 0x1, 0x2, 0x2b5fd20, 0xc4200a0008, 0xc420517c50, 0x0, 0x0)
	/Users/jprice/programs/gopath/src/k8s.io/kops/cmd/kops/create_ig.go:82 +0x171
main.NewCmdCreateInstanceGroup.func1(0xc420429b00, 0xc420459500, 0x1, 0x2)
	/Users/jprice/programs/gopath/src/k8s.io/kops/cmd/kops/create_ig.go:48 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc420429b00, 0xc4204593c0, 0x2, 0x2, 0xc420429b00, 0xc4204593c0)
	/Users/jprice/programs/gopath/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2c34920, 0x1859f00, 0x0, 0x0)
	/Users/jprice/programs/gopath/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x2c34920, 0x2c61c28, 0x0)
	/Users/jprice/programs/gopath/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
	/Users/jprice/programs/gopath/src/k8s.io/kops/cmd/kops/root.go:70 +0x9d
main.main()
	/Users/jprice/programs/gopath/src/k8s.io/kops/cmd/kops/main.go:25 +0x14
```

**Comment by zapman449** [comment]
kops version 1.5.3 built from source on Darwin:

```
go version
go version go1.7.5 darwin/amd64
```

**Comment by zapman449** [comment]
--v=10 logging:

```
kops create ig master-us-west-1a-2 --role=Master --v=10
I0320 15:44:10.449604   93527 loader.go:354] Config loaded from file /Users/jprice/.kube/config
Using cluster from kubectl context: dev-us-east-1c.dev.kuber.pindrop.com

I0320 15:44:11.128090   93527 s3context.go:114] Found bucket "pd-cloud-cspdev2" in region "us-west-1"
I0320 15:44:11.128193   93527 s3fs.go:162] Reading file "s3://pd-cloud-cspdev2/dev-us-east-1c.dev.kuber.pindrop.com/config"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0xde9d2]

goroutine 1 [running]:
panic(0x19bebe0, 0xc420014190)
	/Users/jprice/programs/git/homebrew/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
k8s.io/kops/upup/pkg/fi/cloudup.ChannelForCluster(0x0, 0x2b695e0, 0xc4201c2c00, 0x0)
	/Users/jprice/programs/gopath/src/k8s.io/kops/upup/pkg/fi/cloudup/apply_cluster.go:875 +0x22
main.RunCreateInstanceGroup(0xc4203213c0, 0xc42019c000, 0xc420344f30, 0x1, 0x3, 0x2b5fd20, 0xc4200a2008, 0xc4201c2890, 0x0, 0x0)
	/Users/jprice/programs/gopath/src/k8s.io/kops/cmd/kops/create_ig.go:82 +0x171
main.NewCmdCreateInstanceGroup.func1(0xc42019c000, 0xc420344f30, 0x1, 0x3)
	/Users/jprice/programs/gopath/src/k8s.io/kops/cmd/kops/create_ig.go:48 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc42019c000, 0xc420344d50, 0x3, 0x3, 0xc42019c000, 0xc420344d50)
	/Users/jprice/programs/gopath/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2c34920, 0x1859f00, 0x0, 0x0)
	/Users/jprice/programs/gopath/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x2c34920, 0x2c61c28, 0x0)
	/Users/jprice/programs/gopath/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
	/Users/jprice/programs/gopath/src/k8s.io/kops/cmd/kops/root.go:70 +0x9d
main.main()
	/Users/jprice/programs/gopath/src/k8s.io/kops/cmd/kops/main.go:25 +0x14
```

**Comment by zapman449** [comment]
weird.  Apparently, it's crashing because the cluster it's inferring from $KUBECONFIG 's current-context does not exist in $KOPS_STATE_STORE ???

**Comment by zapman449** [comment]
If I use --name=<right cluster> the command fails, but it doesn't crash (which is reasonable)

**Comment by yissachar** [comment]
Looks like there is some interaction with https://github.com/kubernetes/kops/issues/2078. That issue has now been fixed. Can you try this again using master and see if you still get the panic?

**Comment by chrislovecnm** [comment]
@zapman449 can we close this?

**Comment by zapman449** [comment]
yes.
