### ISSUE TITLE
export command crashed kops

### ISSUE THREAD

**Issue by vorti2** [kubernetes/kops#2719]
Hi,
after I set `export AWS_PROFILE` and `export KOPS_STATE_STORE` to the values that worked before `1.6.0`  the command ```kops export kubecfg --name <cluster name>``` crashed with following lines:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1addeca]

goroutine 1 [running]:
k8s.io/kops/vendor/github.com/aws/aws-sdk-go/aws/session.(*Session).Copy(0x0, 0x0, 0x0, 0x0, 0x3d01f00)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/vendor/github.com/aws/aws-sdk-go/aws/session/session.go:370 +0x3a
k8s.io/kops/vendor/github.com/aws/aws-sdk-go/aws/session.(*Session).clientConfigWithErr(0x0, 0x3cc77e7, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/vendor/github.com/aws/aws-sdk-go/aws/session/session.go:391 +0x98
k8s.io/kops/vendor/github.com/aws/aws-sdk-go/aws/session.(*Session).ClientConfig(0x0, 0x3cc77e7, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/vendor/github.com/aws/aws-sdk-go/aws/session/session.go:385 +0xb2
k8s.io/kops/vendor/github.com/aws/aws-sdk-go/service/ec2.New(0x5456900, 0x0, 0x0, 0x0, 0x0, 0xc420ae84a0)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/vendor/github.com/aws/aws-sdk-go/service/ec2/service.go:48 +0x88
k8s.io/kops/util/pkg/vfs.bruteforceBucketLocation(0xc420aa0660, 0xc42018a640, 0x46, 0xc4209597d8, 0x2)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/util/pkg/vfs/s3context.go:181 +0xdb
k8s.io/kops/util/pkg/vfs.(*S3Context).getRegionForBucket(0xc4204cd980, 0xc420018016, 0x18, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/util/pkg/vfs/s3context.go:140 +0x6d3
k8s.io/kops/util/pkg/vfs.(*S3Path).client(0xc420a8a5c0, 0x3cc6e8e, 0x1, 0xc420959908)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/util/pkg/vfs/s3fs.go:278 +0xbd
k8s.io/kops/util/pkg/vfs.(*S3Path).ReadFile(0xc420a8a5c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/util/pkg/vfs/s3fs.go:168 +0x7c
k8s.io/kops/pkg/client/simple/vfsclientset.(*commonVFS).readConfig(0xc420a63130, 0x5485bc0, 0xc420a8a5c0, 0x2, 0x5485bc0, 0xc420a8a5c0, 0x5485bc0)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/pkg/client/simple/vfsclientset/commonvfs.go:115 +0x49
k8s.io/kops/pkg/client/simple/vfsclientset.(*ClusterVFS).find(0xc420a63130, 0x7fff5fbffbd4, 0x17, 0x5485bc0, 0xc420a8a580, 0xc420a63130)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/pkg/client/simple/vfsclientset/cluster.go:164 +0x104
k8s.io/kops/pkg/client/simple/vfsclientset.(*ClusterVFS).Get(0xc420a63130, 0x7fff5fbffbd4, 0x17, 0x0, 0x0, 0x100eb08)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/pkg/client/simple/vfsclientset/cluster.go:49 +0x3f
main.GetCluster(0xc420a59f20, 0x7fff5fbffbd4, 0x17, 0x0, 0x0, 0x3d21c70)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/cmd/kops/root.go:280 +0xa6
main.(*RootCmd).Cluster(0x557f880, 0xc420aa0080, 0x1, 0x1)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/cmd/kops/root.go:267 +0xb5
main.RunExportKubecfg(0xc420a59f20, 0x5464700, 0xc42000e018, 0xc420a8e280, 0xc420aa0080, 0x1, 0x1, 0x1, 0xc42018a5d0)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/cmd/kops/export_kubecfg.go:76 +0x89
main.NewCmdExportKubecfg.func1(0xc420435200, 0xc420aa0080, 0x1, 0x1)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/cmd/kops/export_kubecfg.go:60 +0x63
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc420435200, 0xc420aa0040, 0x1, 0x1, 0xc420435200, 0xc420aa0040)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5583ba0, 0x35e7f00, 0x0, 0x0)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x5583ba0, 0x55b3628, 0x0)
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/cmd/kops/root.go:98 +0x9b
main.main()
	/private/tmp/kops-20170612-67877-17k1ups/kops-1.6.1/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
```

The new version `1.6.1` does not change anything.

Kind Regards,

Wilhelm

**Comment by vorti2** [comment]
kops Version `1.6.2`  crashes with the the same error message.

**Comment by chrislovecnm** [comment]
How are you setting your state store and your aws profile?

**Comment by vorti2** [comment]
to the values I worked successful in version prior `1.6.0`:
```
export AWS_PROFILE=<name of configuration in ~/.aws/credentials> 
export KOPS_STATE_STORE=s3://<s3 bucket name>
```
Or does the kops not accept AWS_PROFILE for the version `1.6.0` and beyond?

**Comment by vorti2** [comment]
Seems that `kops` has a problem with getting the AWS authentication data from `AWS_PROFILE`.

With `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` it works.
