### ISSUE TITLE
Panic when adding "additionalSecurityGroups" to master IG's

### ISSUE THREAD

**Issue by vascop** [kubernetes/kops#3376]
After doing `kops edit ig master-eu-west-1a` / 1b / 1c and adding:

```
additionalSecurityGroups:
  - sg-1111111
```

To the three of them, I get this:

```
kops update cluster
Using cluster from kubectl context: prod.kops.test.com


*********************************************************************************

A new kubernetes version is available: 1.6.6
Upgrading is recommended (try kops upgrade cluster)

More information: https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_k8s.md#1.6.6

*********************************************************************************

I0913 15:47:17.207237   13909 executor.go:91] Tasks: 0 done / 85 total; 40 can run
I0913 15:47:18.831445   13909 executor.go:91] Tasks: 40 done / 85 total; 13 can run
I0913 15:47:19.404459   13909 executor.go:91] Tasks: 53 done / 85 total; 28 can run
I0913 15:47:21.161408   13909 executor.go:91] Tasks: 81 done / 85 total; 4 can run
I0913 15:47:21.376760   13909 executor.go:91] Tasks: 85 done / 85 total; 0 can run
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x119b3a6]

goroutine 1 [running]:
k8s.io/kops/upup/pkg/fi.(*ResourceHolder).Open(0x0, 0x0, 0x0, 0xc420294400, 0x7fb7dfaa4000)
        /go/src/k8s.io/kops/upup/pkg/fi/resources.go:206 +0x26
k8s.io/kops/upup/pkg/fi.CopyResource(0x4d30440, 0xc420235180, 0x4d31a80, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kops/upup/pkg/fi/resources.go:84 +0x6d
k8s.io/kops/upup/pkg/fi.ResourceAsString(0x4d31a80, 0x0, 0x0, 0x4d31a80, 0x0, 0x4aa601)
        /go/src/k8s.io/kops/upup/pkg/fi/resources.go:102 +0x64
k8s.io/kops/upup/pkg/fi.tryResourceAsString(0x3028d40, 0xc4201014d0, 0x196, 0x4d31a80, 0xc420952520, 0xc420101401)
        /go/src/k8s.io/kops/upup/pkg/fi/dryrun_target.go:348 +0x1ef
k8s.io/kops/upup/pkg/fi.buildChangeList(0x4d32100, 0xc4201014c0, 0x4d32100, 0xc420952540, 0x4d32100, 0xc420101500, 0x0, 0x1, 0x0, 0x0, ...)
        /go/src/k8s.io/kops/upup/pkg/fi/dryrun_target.go:318 +0x8c6
k8s.io/kops/upup/pkg/fi.(*DryRunTarget).PrintReport(0xc4207e9540, 0xc4203d43c0, 0x4d419c0, 0xc42000c018, 0xc421287208, 0x15)
        /go/src/k8s.io/kops/upup/pkg/fi/dryrun_target.go:214 +0x9c9
k8s.io/kops/upup/pkg/fi.(*DryRunTarget).Finish(0xc4207e9540, 0xc4203d43c0, 0x340cbce, 0xa)
        /go/src/k8s.io/kops/upup/pkg/fi/dryrun_target.go:475 +0x47
k8s.io/kops/upup/pkg/fi/cloudup.(*ApplyClusterCmd).Run(0xc42017a5b0, 0x0, 0x0)
        /go/src/k8s.io/kops/upup/pkg/fi/cloudup/apply_cluster.go:786 +0x4ae6
main.RunUpdateCluster(0xc4207ef120, 0xc420a1f940, 0x14, 0x4d419c0, 0xc42000c018, 0xc42034e7e0, 0x4, 0xc420667cf0)
        /go/src/k8s.io/kops/cmd/kops/update_cluster.go:215 +0x650
main.NewCmdUpdateCluster.func1(0xc4203a66c0, 0x4ef9698, 0x0, 0x0)
        /go/src/k8s.io/kops/cmd/kops/update_cluster.go:99 +0xd8
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203a66c0, 0x4ef9698, 0x0, 0x0, 0xc4203a66c0, 0x4ef9698)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4ec8b80, 0x2cb8f00, 0x0, 0x0)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x4ec8b80, 0x4ef9698, 0x0)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
        /go/src/k8s.io/kops/cmd/kops/root.go:98 +0x9b
main.main()
        /go/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
```

I didn't have any `additionalSecurityGroups` defined before. This happens in versions 1.6.0/1.6.2/1.7.0. Is there anything I can do to avoid this?

**Comment by robinpercy** [comment]
@vascop, I tried to reproduce on 1.7.0 (OS X) but failed.  Any other details you can provide that may be relevant?

```
$ kops update cluster
Using cluster from kubectl context: kops.robin.trinimbus.org

I0913 22:36:43.328934   39137 executor.go:91] Tasks: 0 done / 76 total; 39 can run
I0913 22:36:44.225956   39137 executor.go:91] Tasks: 39 done / 76 total; 14 can run
I0913 22:36:44.723989   39137 executor.go:91] Tasks: 53 done / 76 total; 19 can run
I0913 22:36:45.781511   39137 executor.go:91] Tasks: 72 done / 76 total; 4 can run
I0913 22:36:45.910734   39137 executor.go:91] Tasks: 76 done / 76 total; 0 can run
Will modify resources:
  LaunchConfiguration/master-us-west-2a.masters.kops.robin.trinimbus.org
        SecurityGroups           [id:sg-f38d6c8e] -> [name:masters.kops.robin.trinimbus.org id:sg-f38d6c8e, name:sg-fa8a6b87 id:sg-fa8a6b87]

  LaunchConfiguration/master-us-west-2b.masters.kops.robin.trinimbus.org
        SecurityGroups           [id:sg-f38d6c8e] -> [name:masters.kops.robin.trinimbus.org id:sg-f38d6c8e, name:sg-fa8a6b87 id:sg-fa8a6b87]

  LaunchConfiguration/master-us-west-2c.masters.kops.robin.trinimbus.org
        SecurityGroups           [id:sg-f38d6c8e] -> [name:masters.kops.robin.trinimbus.org id:sg-f38d6c8e, name:sg-fa8a6b87 id:sg-fa8a6b87]

Must specify --yes to apply changes
```

**Comment by vascop** [comment]
I've run it directly with --yes since the panic was in `/go/src/k8s.io/kops/upup/pkg/fi/dryrun_target.go`. This avoided the issue, but the code is still broken. I unfortunately do not know enough Go to be productive debugging this at the moment.

**Comment by chrislovecnm** [comment]
@vascop can we get a kops version?

**Comment by vascop** [comment]
@chrislovecnm Like I said in the first post this happened with versions 1.6.0, 1.6.2 and 1.7.0. I didn't try any others.

**Comment by chrislovecnm** [comment]
Can you post the full ig yaml?

**Comment by chrislovecnm** [comment]
Here is an example for using sec groups that we use for testing https://github.com/kubernetes/kops/blob/master/tests/integration/complex/in-v1alpha2.yaml

**Comment by vascop** [comment]
@chrislovecnm The ig yaml:
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-06-02T15:14:35Z
  labels:
    kops.k8s.io/cluster: prod.kops.test.com
  name: master-eu-west-1a
spec:
  additionalSecurityGroups:
  - sg-10b8e068
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-west-1a
```

Here is the end of the output from running `kops update cluster -v 10` with that ig yaml (panic still happens after having applied the changes already): https://gist.github.com/vascop/ba8cfda89d875e55af0b8f7f5bf42f82

There's nothing suspicious in the rest of the output that I can see, it looks like the issue is when trying to delete the tmp deploy directory? I can't find any logging saying it's creating that dir and I also can't find that directory while the update is running. This happens if I run it with a OS superuser as well so it doesn't look like a permissions issue.

**Comment by vascop** [comment]
After running this with --yes like mentioned previously to avoid the panic in "dryrun" code, now lost all ability to ever not run "--yes" as kops always panics in the same spot. Following the traceback the crash is caused when printing the list of changes, one of the resources being converted to a string apparently.

**Comment by chrislovecnm** [comment]
/lifecycle frozen
/remove-lifecycle stale

Can someone validate that this is fixed in master?

**Comment by joekohlsdorf** [comment]
Just tried this on 1.16.0 against a cluster running 1.16.7 and faced no issues.

**Comment by rifelpet** [comment]
closing since this is no longer reproducible

/close
