### ISSUE TITLE
 signal SIGSEGV: segmentation violation with --bastion --topology private options enabled

### ISSUE THREAD

**Issue by yahavb** [kubernetes/kops#3555]
Any idea what is the reason for the segmentation violation I get after executing:
```+ kops create cluster gce-use1-demo1-int.example.com --zones us-east1-b,us-east1-c,us-east1-d --master-zones us-east1-b,us-east1-c,us-east1-d --node-count 1 --dns private --topology private --bastion=true --project eadpcloud-dev-gcp --image ubuntu-os-cloud/ubuntu-1604-xenial-v20170202 --cloud gce --yes --networking kube-router
I1006 15:56:59.250220   32542 create_cluster.go:845] Using SSH public key: /Users/ybiran/.ssh/id_rsa.pub
I1006 15:56:59.250497   32542 subnets.go:183] Assigned CIDR 172.20.32.0/19 to subnet us-east1-b
I1006 15:56:59.250518   32542 subnets.go:183] Assigned CIDR 172.20.64.0/19 to subnet us-east1-c
I1006 15:56:59.250530   32542 subnets.go:183] Assigned CIDR 172.20.96.0/19 to subnet us-east1-d
I1006 15:56:59.250542   32542 subnets.go:197] Assigned CIDR 172.20.0.0/22 to subnet utility-us-east1-b
I1006 15:56:59.250555   32542 subnets.go:197] Assigned CIDR 172.20.4.0/22 to subnet utility-us-east1-c
I1006 15:56:59.250567   32542 subnets.go:197] Assigned CIDR 172.20.8.0/22 to subnet utility-us-east1-d
I1006 15:56:59.252154   32542 clouddns.go:86] Using DefaultTokenSource &oauth2.reuseTokenSource{new:jwt.jwtSource{ctx:(*context.emptyCtx)(0xc420010268), conf:(*jwt.Config)(0xc42061bb00)}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
I1006 15:56:59.252186   32542 clouddns.go:100] Successfully got DNS service: &{0xc420c4bdd0 https://www.googleapis.com/dns/v1/projects/  0xc42000d628 0xc42000d630 0xc42000d638 0xc42000d640}
I1006 15:57:04.337931   32542 clouddns.go:86] Using DefaultTokenSource &oauth2.reuseTokenSource{new:jwt.jwtSource{ctx:(*context.emptyCtx)(0xc420010268), conf:(*jwt.Config)(0xc420dadc80)}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
I1006 15:57:04.337972   32542 clouddns.go:100] Successfully got DNS service: &{0xc420d51890 https://www.googleapis.com/dns/v1/projects/  0xc42009a7c8 0xc42009a7d0 0xc42009a7d8 0xc42009a7e0}
I1006 15:57:06.111826   32542 dns.go:91] Private DNS: skipping DNS validation
W1006 15:57:06.127343   32542 external_access.go:36] TODO: Harmonize gcemodel ExternalAccessModelBuilder with awsmodel
W1006 15:57:06.127361   32542 firewall.go:35] TODO: Harmonize gcemodel with awsmodel for firewall - GCE model is way too open
W1006 15:57:06.127367   32542 firewall.go:63] Adding overlay network for X -> node rule - HACK
W1006 15:57:06.127370   32542 firewall.go:64] We should probably use subnets?
W1006 15:57:06.127384   32542 firewall.go:118] Adding overlay network for X -> master rule - HACK
I1006 15:57:08.080349   32542 executor.go:91] Tasks: 0 done / 57 total; 34 can run
I1006 15:57:08.834281   32542 vfs_castore.go:422] Issuing new certificate: "kube-controller-manager"
I1006 15:57:08.872526   32542 vfs_castore.go:422] Issuing new certificate: "kubecfg"
I1006 15:57:08.912892   32542 vfs_castore.go:422] Issuing new certificate: "kube-proxy"
I1006 15:57:08.944757   32542 vfs_castore.go:422] Issuing new certificate: "kubelet"
I1006 15:57:08.946417   32542 vfs_castore.go:422] Issuing new certificate: "kube-router"
I1006 15:57:09.117861   32542 vfs_castore.go:422] Issuing new certificate: "kops"
I1006 15:57:09.358936   32542 vfs_castore.go:422] Issuing new certificate: "kube-scheduler"
W1006 15:57:11.834956   32542 executor.go:109] error running task "Disk/d-etcd-events-gce-use1-demo1-int-darkside-ea-com" (9m56s remaining to succeed): Cannot apply changes to Disk: *gcetasks.Disk {"Name":null,"Lifecycle":"Sync","VolumeType":null,"SizeGB":null,"Zone":null,"Labels":null}
W1006 15:57:11.834999   32542 executor.go:109] error running task "Disk/c-etcd-events-gce-use1-demo1-int-darkside-ea-com" (9m56s remaining to succeed): Cannot apply changes to Disk: *gcetasks.Disk {"Name":null,"Lifecycle":"Sync","VolumeType":null,"SizeGB":null,"Zone":null,"Labels":null}
W1006 15:57:11.835017   32542 executor.go:109] error running task "Disk/b-etcd-events-gce-use1-demo1-int-darkside-ea-com" (9m56s remaining to succeed): Cannot apply changes to Disk: *gcetasks.Disk {"Name":null,"Lifecycle":"Sync","VolumeType":null,"SizeGB":null,"Zone":null,"Labels":null}
W1006 15:57:11.835031   32542 executor.go:109] error running task "Disk/b-etcd-main-gce-use1-demo1-int-darkside-ea-com" (9m56s remaining to succeed): Cannot apply changes to Disk: *gcetasks.Disk {"Name":null,"Lifecycle":"Sync","VolumeType":null,"SizeGB":null,"Zone":null,"Labels":null}
W1006 15:57:11.835046   32542 executor.go:109] error running task "Disk/d-etcd-main-gce-use1-demo1-int-darkside-ea-com" (9m56s remaining to succeed): Cannot apply changes to Disk: *gcetasks.Disk {"Name":null,"Lifecycle":"Sync","VolumeType":null,"SizeGB":null,"Zone":null,"Labels":null}
W1006 15:57:11.835060   32542 executor.go:109] error running task "Disk/c-etcd-main-gce-use1-demo1-int-darkside-ea-com" (9m56s remaining to succeed): Cannot apply changes to Disk: *gcetasks.Disk {"Name":null,"Lifecycle":"Sync","VolumeType":null,"SizeGB":null,"Zone":null,"Labels":null}
I1006 15:57:11.835086   32542 executor.go:91] Tasks: 28 done / 57 total; 20 can run
I1006 15:57:12.038932   32542 instancetemplate.go:203] We should be using NVME for GCE
I1006 15:57:12.042506   32542 instancetemplate.go:203] We should be using NVME for GCE
I1006 15:57:12.051365   32542 instancetemplate.go:203] We should be using NVME for GCE
I1006 15:57:12.056189   32542 instancetemplate.go:203] We should be using NVME for GCE
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1d9c8c2]

goroutine 470 [running]:
k8s.io/kops/upup/pkg/fi.(*ResourceHolder).AsString(0x0, 0xc420d1a840, 0xc420ba7560, 0x0, 0x1)
	/go/src/k8s.io/kops/upup/pkg/fi/resources.go:230 +0x22
k8s.io/kops/upup/pkg/fi/cloudup/gcetasks.(*InstanceTemplate).mapToGCE(0xc420dd6ea0, 0xc420db74e0, 0x11, 0x0, 0xc421063220, 0x0)
	/go/src/k8s.io/kops/upup/pkg/fi/cloudup/gcetasks/instancetemplate.go:258 +0xa3c
k8s.io/kops/upup/pkg/fi/cloudup/gcetasks.(*InstanceTemplate).Find(0xc420dd6ea0, 0xc420160d80, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kops/upup/pkg/fi/cloudup/gcetasks/instancetemplate.go:80 +0x2c4
reflect.Value.call(0x3eaab00, 0xc420dd6ea0, 0xa13, 0x4004a99, 0x4, 0xc420da00a0, 0x1, 0x1, 0xc420df4048, 0x13, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x3eaab00, 0xc420dd6ea0, 0xa13, 0xc420da00a0, 0x1, 0x1, 0xc420dd6ea0, 0xa13, 0xc420340000)
	/usr/local/go/src/reflect/value.go:302 +0xa4
k8s.io/kops/upup/pkg/fi/utils.InvokeMethod(0x3eaab00, 0xc420dd6ea0, 0x4004b19, 0x4, 0xc4209e5df8, 0x1, 0x1, 0x0, 0xc42084fe18, 0x1068572, ...)
	/go/src/k8s.io/kops/upup/pkg/fi/utils/reflect.go:75 +0x40e
k8s.io/kops/upup/pkg/fi.invokeFind(0x59343e0, 0xc420dd6ea0, 0xc420160d80, 0x0, 0x0, 0xc42005a400, 0x8)
	/go/src/k8s.io/kops/upup/pkg/fi/default_methods.go:115 +0xc1
k8s.io/kops/upup/pkg/fi.DefaultDeltaRunMethod(0x59343e0, 0xc420dd6ea0, 0xc420160d80, 0xc42024e2a8, 0xc420df6300)
	/go/src/k8s.io/kops/upup/pkg/fi/default_methods.go:45 +0x7a4
k8s.io/kops/upup/pkg/fi/cloudup/gcetasks.(*InstanceTemplate).Run(0xc420dd6ea0, 0xc420160d80, 0x16, 0xc42084ff78)
	/go/src/k8s.io/kops/upup/pkg/fi/cloudup/gcetasks/instancetemplate.go:171 +0x41
k8s.io/kops/upup/pkg/fi.(*executor).forkJoin.func1(0xc420d9f680, 0x14, 0x14, 0xc420d16c70, 0xc420da4008, 0xc42024e2a0, 0x5)
	/go/src/k8s.io/kops/upup/pkg/fi/executor.go:158 +0x1ea
created by k8s.io/kops/upup/pkg/fi.(*executor).forkJoin
	/go/src/k8s.io/kops/upup/pkg/fi/executor.go:159 +0x123```

**Comment by chrislovecnm** [comment]
private topology and bastions are not supported on gce, this is a bug, and an issue with validation :)

**Comment by chrislovecnm** [comment]
@yahavb what version of kops are you on?

**Comment by chrislovecnm** [comment]
@yahavb so playing around some.

### Findings

When you turn off the public ip address for a GCE instance, it no longer has access to the external internet.

1. GCE does not have a NAT GW support offering.  We would need to add nat gw support in kops, for GCE instances to have internet access w/o a public ip address.  Another option is setting up a https proxy, that the instances can access.  We have https proxy support in kops currently.
2. Having a bastion w/o private instances just does not make sense.
3. When the assests API gets finished, you could feasibly have completely airgapped instances, so you may not need NAT, and thus have private IP addresses.  Hopefully over the next two weeks I will have time to finish the hosted assets in kops.

So we can implement this, but need to have the user to setup a squid or http/https proxy.

### Bugs

We do have a couple of bugs that I will push in a seperate PR, and we do not have support for turning off the public ip address on the GCE instance as of yet.

**Comment by yahavb** [comment]
I am using the latest kops I pulled from Oct 10th.

**Comment by yahavb** [comment]
@chrislovecnm is the http/s proxy to be deployed externally outside of the cluster? Or is it something to be deployed as a workload in the new cluster?

**Comment by chrislovecnm** [comment]
Has to be external to the cluster, or k8s will not start. We may be able to use assests API which is not done, but I do not know how nodeup will act
