### ISSUE TITLE
crash when 

### ISSUE THREAD

**Issue by st33v** [kubernetes/kops#3855]
-------------BUG REPORT --------------------
1. Fill in as much of the template below as you can. 

2. What kops version are you running? use `kops version`
kops-1.7.1

3. What Kubernetes version are you running? use `kubectl version`
```json
{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-09T07:27:47Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
```

4. What cloud provider are you using?
AWS GovCloud

5. What commands did you execute (Please provide cluster manifest `kops get --name my.example.com`, if available) and what happened after commands executed?
kops create cluster --dns private --state=${KOPS_STATE_STORE} --zones=us-gov-west-1a,us-gov-west-1b  ${CLUSTER_FULL_NAME}

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b0a0ca]

goroutine 1 [running]:
k8s.io/kops/vendor/github.com/aws/aws-sdk-go/aws/session.(*Session).Copy(0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/vendor/github.com/aws/aws-sdk-go/aws/session/session.go:370 +0x3a
k8s.io/kops/vendor/github.com/aws/aws-sdk-go/aws/session.(*Session).clientConfigWithErr(0x0, 0x3f1faf3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/vendor/github.com/aws/aws-sdk-go/aws/session/session.go:391 +0x98
k8s.io/kops/vendor/github.com/aws/aws-sdk-go/aws/session.(*Session).ClientConfig(0x0, 0x3f1faf3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/vendor/github.com/aws/aws-sdk-go/aws/session/session.go:385 +0xdd
k8s.io/kops/vendor/github.com/aws/aws-sdk-go/service/ec2.New(0x59f6a20, 0x0, 0x0, 0x0, 0x0, 0xc420b1a480)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/vendor/github.com/aws/aws-sdk-go/service/ec2/service.go:48 +0x88
k8s.io/kops/util/pkg/vfs.bruteforceBucketLocation(0xc420ab93e0, 0xc420096610, 0x46, 0xc4209c6b70, 0x2)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/util/pkg/vfs/s3context.go:183 +0xd6
k8s.io/kops/util/pkg/vfs.(*S3Context).getRegionForBucket(0xc4205002e0, 0x7fff5fbff9af, 0xf, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/util/pkg/vfs/s3context.go:142 +0x753
k8s.io/kops/util/pkg/vfs.(*S3Path).client(0xc420aa5d00, 0x9, 0x3f1f1ee, 0xc4209c6cb0)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/util/pkg/vfs/s3fs.go:278 +0xc6
k8s.io/kops/util/pkg/vfs.(*S3Path).ReadFile(0xc420aa5d00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/util/pkg/vfs/s3fs.go:168 +0x7c
k8s.io/kops/pkg/client/simple/vfsclientset.(*commonVFS).readConfig(0xc4205a5f40, 0x5a29d80, 0xc420aa5d00, 0x2, 0x5a29d80, 0xc420aa5d00, 0x5a0c501)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/pkg/client/simple/vfsclientset/commonvfs.go:117 +0x49
k8s.io/kops/pkg/client/simple/vfsclientset.(*ClusterVFS).find(0xc4205a5f40, 0x7fff5fbff9e5, 0x9, 0x1d58697, 0x5a29d80, 0xc420aa5cc0)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/pkg/client/simple/vfsclientset/cluster.go:169 +0x102
k8s.io/kops/pkg/client/simple/vfsclientset.(*ClusterVFS).Get(0xc4205a5f40, 0x7fff5fbff9e5, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/pkg/client/simple/vfsclientset/cluster.go:54 +0xb4
k8s.io/kops/pkg/client/simple/vfsclientset.(*VFSClientset).GetCluster(0xc420ab93c0, 0x7fff5fbff9e5, 0x9, 0x0, 0x0, 0x0)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/pkg/client/simple/vfsclientset/clientset.go:42 +0x82
main.RunCreateCluster(0xc42062c200, 0x5a05ce0, 0xc420096008, 0xc4207d1600, 0x0, 0x0)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/cmd/kops/create_cluster.go:334 +0x1cd
main.NewCmdCreateCluster.func1(0xc4202618c0, 0xc4205a5ef0, 0x1, 0x5)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/cmd/kops/create_cluster.go:214 +0x135
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202618c0, 0xc4205a5db0, 0x5, 0x5, 0xc4202618c0, 0xc4205a5db0)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x234
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5b953c0, 0x37d1f00, 0x0, 0x0)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x5b953c0, 0x5bc9980, 0x0)
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/cmd/kops/root.go:98 +0x91
main.main()
	/private/tmp/kops-20171009-38210-pfm0me/kops-1.7.1/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
```

6. What you expected to happen:
I didn't expect a panic. I have deployed to non-govcloud accounts without issue. Seems to be unable to get a session on the s3 bucket. 

7. How can we to reproduce it (as minimally and precisely as possible):
try a KOPS how-to in GovCloud

8. Anything else do we need to know:

**Comment by chrislovecnm** [comment]
@st33v can you try the latest kops beta?  I think this is fixed

**Comment by chrislovecnm** [comment]
I edited your log posting btw. so I could read it better

**Comment by st33v** [comment]
wow. thanks. I noticed that the beta had been released suddenly so I installed it and now I get:
```shell
 sneuharth@sneuharth-mbp  ~  kops create cluster --dns private --state=${KOPS_STATE_STORE} --name=${CLUSTER_FULL_NAME}                                 1 ↵  10233  17:06:54

error reading cluster configuration "bi.gc.gdi": error reading s3://bi.gc.gdi-state/bi.gc.gdi/config: error connecting to S3: error starting new AWS session: SharedConfigLoadError: failed to load config file, /Users/sneuharth/.aws/credentials
```
I suspect that SharedStateConfig isn't using the [govcloud endpoints](http://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html). The bucket is there, I promise. And I can list it's contents using the creds from /Users/sneuharth/.aws/credentials. 

```

**Comment by chrislovecnm** [comment]
>  failed to load config file, /Users/sneuharth/.aws/credential

Seems odd.  What env variables do you have setup?

**Comment by st33v** [comment]
I don't have anything related to AWS exported. I've started a new shell and get the same error.

**Comment by st33v** [comment]
Yeah, I just don't get it. The AWS cli works fine and I can 'ls' the bucket that I created for state. It's like the underlying golang AWS lib is misconfigured. And keep in mind, This works if I flip over to non-govCloud AWS accounts. 

Maybe I should run some govCloud 'enabled' tests on the golang AWS libs?

**Comment by chrislovecnm** [comment]
There is a debug logging mode that you can give the aws client, you have to recompile kops. There is an open issue to make it configurable.

Getting that probably would be helpful.

**Comment by st33v** [comment]
I can totally do that. Do you happen to know the var to tweak in the AWS libs?

I noticed that the AWS libs in vendor/ are pretty old. Any chance there's going to be an update? I wonder if this is fixed upstream and 'just works' with a newer version.

**Comment by chrislovecnm** [comment]
It is an open issue in kops to add aws debug support. I am not certain if it is fixed upstream. It is in the creation of the aws session

**Comment by st33v** [comment]
OK, I found the problem. The aws session/shared_config.go code was choking on my 'invalid' INI file (~/.aws/credentials) which contained a comment on the [default] line.

Thanks for listening. ;)

**Comment by vorti2** [comment]
I have a comment on another line, I deleted it and afterwards it worked.
