### ISSUE TITLE
Protokube fails when restarting journald

### ISSUE THREAD

**Issue by mzahn86** [kubernetes/kops#4161]
1. What `kops` version are you running? 
> Version 1.8.0 (git-5099bc5)

2. What Kubernetes version are you running? 

> Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

> Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
> aws

4. What commands did you run?  What is the simplest way to reproduce this issue?
```
kops create cluster \        
--zones eu-central-1a,eu-central-1b,eu-central-1c \
--master-zones eu-central-1a,eu-central-1b,eu-central-1c \
--networking weave \
--vpc ${My_Existing_VPC_ID} \
--node-count 3 \
--master-count 3 \
--node-size m4.large \
--master-size m4.large \
--ssh-public-key /path/to/my/public/key \
protokube.test.k8s.local

```
Then restart journald service on a node/master:
> systemctl restart systemd-journald 

5. What happened after the commands executed?
Protokube.service tries to restart every second.
It fails since it is already running and the port is already used.
Every second multiple ec2-requests are made which causes followup issues like ec2 RequestLimitExceeded responses.
The cluster itself stays operational.

Excerpt of journalctl
```
Dec 28 11:54:43 ip-172-31-93-175 systemd[1]: Unit protokube.service entered failed state.
Dec 28 11:54:43 ip-172-31-93-175 systemd[1]: protokube.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: /go/src/k8s.io/kops/protokube/cmd/protokube/main.go:223 +0x23eb
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: created by main.run
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: /go/src/k8s.io/kops/protokube/cmd/protokube/main.go:217 +0x2f
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: main.run.func1(0xc4203e1110)
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: /go/src/k8s.io/kops/protokube/pkg/gossip/mesh/gossip.go:86 +0x45
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: k8s.io/kops/protokube/pkg/gossip/mesh.(*MeshGossiper).Start(0xc4203e1110, 0x0, 0x0)
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: /go/src/k8s.io/kops/vendor/github.com/weaveworks/mesh/router.go:84 +0x2b
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: k8s.io/kops/vendor/github.com/weaveworks/mesh.(*Router).Start(0xc420136000)
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: /go/src/k8s.io/kops/vendor/github.com/weaveworks/mesh/router.go:105 +0x188
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: k8s.io/kops/vendor/github.com/weaveworks/mesh.(*Router).listenTCP(0xc420136000)
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: goroutine 59 [running]:
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: panic: listen tcp4 0.0.0.0:3999: bind: address already in use
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: I1228 11:54:43.206721   16891 aws_volume.go:72] AWS API Request: ec2/DescribeInstances
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: I1228 11:54:43.203855   16891 aws_volume.go:72] AWS API Request: ec2metadata/GetMetadata
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: I1228 11:54:43.202792   16891 aws_volume.go:72] AWS API Request: ec2metadata/GetMetadata
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: I1228 11:54:43.201643   16891 aws_volume.go:72] AWS API Request: ec2metadata/GetMetadata
Dec 28 11:54:43 ip-172-31-93-175 docker[16865]: protokube version 0.1
Dec 28 11:54:42 ip-172-31-93-175 systemd[1]: Started Kubernetes Protokube Service.
Dec 28 11:54:42 ip-172-31-93-175 systemd[1]: Starting Kubernetes Protokube Service...
Dec 28 11:54:42 ip-172-31-93-175 systemd[1]: Stopping Kubernetes Protokube Service...
Dec 28 11:54:42 ip-172-31-93-175 systemd[1]: protokube.service holdoff time over, scheduling restart.
```

6. What did you expect to happen?
Protokube should not be affected by journald restarts

7. Please provide your cluster manifest.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-12-28T09:04:29Z
  name: protokube.test.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://test.kops/protokube.test.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.4
  masterInternalName: api.internal.protokube.test.k8s.local
  masterPublicName: api.protokube.test.k8s.local
  networkCIDR: 172.31.0.0/16
  networkID: MY-VPC
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.31.91.0/24
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  - cidr: 172.31.92.0/24
    name: eu-central-1b
    type: Public
    zone: eu-central-1b
  - cidr: 172.31.93.0/24
    name: eu-central-1c
    type: Public
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-28T09:04:29Z
  labels:
    kops.k8s.io/cluster: protokube.test.k8s.local
  name: master-eu-central-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-28T09:04:30Z
  labels:
    kops.k8s.io/cluster: protokube.test.k8s.local
  name: master-eu-central-1b
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  subnets:
  - eu-central-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-28T09:04:30Z
  labels:
    kops.k8s.io/cluster: protokube.test.k8s.local
  name: master-eu-central-1c
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  subnets:
  - eu-central-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-28T09:04:30Z
  labels:
    kops.k8s.io/cluster: protokube.test.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c

```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
N/A

9. Anything else do we need to know?
We limit forwarding of journald for preventing full hard disk drives on the nodes/masters.
Therefore, we restart journald once after updating its config.

**Comment by cciotti** [comment]
I'm also seeing this

**Comment by sciyoshi** [comment]
I am seeing this issue as well. See also #5145 which might be related.

/remove-lifecycle rotten

**Comment by justinsb** [comment]
I tried reproducing this with latest and wasn't able to - when I restarted systemd-journald protokube continued uninterrupted; I tried restarting the protokube service and it killed the docker container as well.

I'll try again with kops 1.8, but going to mark this for the 1.11 milestone as it isn't obviously still happening.

**Comment by rdrgmnzs** [comment]
I was also not able to reproduce on ubuntu 16.04 when restarting journald 
Kops 1.10 
Kubernetes 1.10

**Comment by rbtcollins** [comment]
/remove-lifecycle rotten

The port is being used:
```root@ip-172-20-39-30:~# netstat -4apn | grep 3999
tcp        0      0 0.0.0.0:3999            0.0.0.0:*               LISTEN      14944/protokube
tcp        0      0 172.20.39.30:3999       172.20.46.2:35698       ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:36896      172.20.54.1:3999        ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:3999       172.20.41.169:27029     ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:3999       172.20.57.92:47264      ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:37698      172.20.46.193:3999      ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:61647      172.20.40.3:3999        ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:21805      172.20.57.0:3999        ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:19486      172.20.55.232:3999      ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:27418      172.20.51.225:3999      ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:3999       172.20.48.138:20886     ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:3999       172.20.42.22:60440      ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:10746      172.20.49.86:3999       ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:11594      172.20.53.95:3999       ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:12656      172.20.43.174:3999      ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:24782      172.20.55.244:3999      ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:15333      172.20.58.152:3999      ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:3999       172.20.48.138:26018     ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:60426      172.20.50.4:3999        ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:44776      172.20.45.82:3999       ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:14557      172.20.44.124:3999      ESTABLISHED 14944/protokube
tcp        0      0 172.20.39.30:32362      172.20.42.136:3999      ESTABLISHED 14944/protokube
```

**Comment by rbtcollins** [comment]
Probably the port open just needs SO_REUSEADDR supplied, since we know we want to open the socket rapidly when a failure has occured.
