### ISSUE TITLE
bazel-crossbuild-protokube-image brew python broken

### ISSUE THREAD

**Issue by mikesplain** [kubernetes/kops#4596]
When running `make bazel-crossbuild-protokube-image` on mac os you expect an image to be built.

[As of March 1st](https://brew.sh/2018/01/19/homebrew-1.5.0/), homebrew now considers python == python3 rather than python 2.

This may lead to an error like:

<details>
  <summary>Click to expand</summary>

```
ERROR: Skipping '//images:protokube.tar': error loading package 'images': Encountered error while reading extension file 'file/packages.bzl': no such package '@package_bundle//file': no such package '@debian_stretch//file': dpkg_parser command failed: Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/var/tmp/_bazel_mikesplain/0b08596454ccfeb191e11d822b5dc7c9/external/dpkg_parser/file/dpkg_parser.par/__main__.py", line 22, in <module>
ModuleNotFoundError: No module named 'urllib2'
 (/private/var/tmp/_bazel_mikesplain/0b08596454ccfeb191e11d822b5dc7c9/external/dpkg_parser/file/dpkg_parser.par --download-and-extract-only=True --mirror-url=http://snapshot.debian.org/archive --arch=amd64 --distro=stretch --snapshot=20171101T160520Z --packages-gz-url= --package-prefix= --sha256=9aea0e4c9ce210991c6edcb5370cb9b11e9e554a0f563e7754a4028a8fd0cb73)
WARNING: Target pattern parsing failed.
ERROR: error loading package 'images': Encountered error while reading extension file 'file/packages.bzl': no such package '@package_bundle//file': no such package '@debian_stretch//file': dpkg_parser command failed: Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/var/tmp/_bazel_mikesplain/0b08596454ccfeb191e11d822b5dc7c9/external/dpkg_parser/file/dpkg_parser.par/__main__.py", line 22, in <module>
ModuleNotFoundError: No module named 'urllib2'
 (/private/var/tmp/_bazel_mikesplain/0b08596454ccfeb191e11d822b5dc7c9/external/dpkg_parser/file/dpkg_parser.par --download-and-extract-only=True --mirror-url=http://snapshot.debian.org/archive --arch=amd64 --distro=stretch --snapshot=20171101T160520Z --packages-gz-url= --package-prefix= --sha256=9aea0e4c9ce210991c6edcb5370cb9b11e9e554a0f563e7754a4028a8fd0cb73)
INFO: Elapsed time: 3.946s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: images
```
</details>

This breakage occurs becase urlib2 doesn't exist for python3.

A quick workaround is to run `brew unlink python` then rerun the above command however we should consider long term affects of this breakage simply for this image.

**Comment by mikesplain** [comment]
Or a simple 
```
rm -rf `which python`
```
can solve it, temporarily.

**Comment by mikesplain** [comment]
`brew info python@2` also helps and makes the above suggestion moot:

>This formula installs a python2 executable to /usr/local/opt/python@2/bin
If you wish to have this formula's python executable in your PATH then add
the following to ~/.zshrc:
  `export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"`

**Comment by mikesplain** [comment]
Since the brew change was reverted, this shouldn't really be an issue for anyone at the moment... closing.
