### ISSUE TITLE
Creating a new ig following the docs is missing information, causing segv

### ISSUE THREAD

**Issue by peterkuiper** [kubernetes/kops#4664]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

`1.8.1`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

`1.8.6`

3. What cloud provider are you using?

`AWS`

4. What commands did you run?  What is the simplest way to reproduce this issue?

`kops create ig nodes-eu-central-1b --subnet eu-central-1b --state s3://... -v 10`

5. What happened after the commands executed?

```
I0310 11:10:47.018875   64672 loader.go:357] Config loaded from file /.../.kube/config
Using cluster from kubectl context: ...

I0310 11:10:47.668806   64672 s3context.go:163] Found bucket "..." in region "us-east-1"
I0310 11:10:47.668891   64672 s3fs.go:176] Reading file ".../.../config"
I0310 11:10:48.243417   64672 channel.go:93] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I0310 11:10:48.243458   64672 channel.go:98] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I0310 11:10:48.243476   64672 context.go:140] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I0310 11:10:48.459092   64672 channel.go:107] Channel contents: spec:
  images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.7.0 <1.8.0"
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.8.0 <1.9.0"
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.9.0 <1.10.0"
    # Need stretch as default in 1.10 (for nvme)
    # BUT... this is causing the submit queue to block, so back to jessie temporarily: https://github.com/kubernetes/kubernetes/issues/56763
    - name: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
      providerID: aws
      kubernetesVersion: ">=1.10.0"
    - providerID: gce
      name: "cos-cloud/cos-stable-60-9592-90-0"
  cluster:
    kubernetesVersion: v1.5.8
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.9.0"
    recommendedVersion: 1.9.3
    requiredVersion: 1.9.0
  - range: ">=1.8.0"
    recommendedVersion: 1.8.6
    requiredVersion: 1.8.0
  - range: ">=1.7.0"
    recommendedVersion: 1.7.11
    requiredVersion: 1.7.0
  - range: ">=1.6.0"
    recommendedVersion: 1.6.13
    requiredVersion: 1.6.0
  - range: ">=1.5.0"
    recommendedVersion: 1.5.8
    requiredVersion: 1.5.1
  - range: "<1.5.0"
    recommendedVersion: 1.4.12
    requiredVersion: 1.4.2
  kopsVersions:
  - range: ">=1.9.0-alpha.1"
    recommendedVersion: 1.9.0-alpha.1
    #requiredVersion: 1.9.0-alpha.1
    kubernetesVersion: 1.9.3
  - range: ">=1.8.0-alpha.1"
    recommendedVersion: 1.8.0
    #requiredVersion: 1.8.0
    kubernetesVersion: 1.8.6
  - range: ">=1.7.0-alpha.1"
    recommendedVersion: 1.7.1
    #requiredVersion: 1.7.0
    kubernetesVersion: 1.7.11
  - range: ">=1.6.0-alpha.1"
    #recommendedVersion: 1.6.0
    #requiredVersion: 1.6.0
    kubernetesVersion: 1.6.13
  - range: ">=1.5.0-alpha1"
    recommendedVersion: 1.5.1
    #requiredVersion: 1.5.1
    kubernetesVersion: 1.5.8
  - range: "<1.5.0"
    recommendedVersion: 1.4.4
    #requiredVersion: 1.4.4
    kubernetesVersion: 1.4.12
I0310 11:10:48.459423   64672 s3fs.go:176] Reading file "s3://.../.../instancegroup/nodes-eu-central-1b"
I0310 11:10:48.586402   64672 aws_utils.go:39] Querying EC2 for all valid regions
I0310 11:10:49.180738   64672 aws_cloud.go:956] Querying EC2 for all valid zones in region "eu-central-1"
I0310 11:10:49.180867   64672 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1e0 pc=0x31bd43f]

goroutine 1 [running]:
k8s.io/kops/pkg/apis/kops.(*InstanceGroup).AddInstanceGroupNodeLabel(...)
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/pkg/apis/kops/instancegroup.go:172
main.RunCreateInstanceGroup(0xc420192b00, 0xc4202da900, 0xc42011f340, 0x1, 0x7, 0x57389e0, 0xc420094008, 0xc42061ec80, 0x0, 0x0)
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/create_ig.go:160 +0x2ff
main.NewCmdCreateInstanceGroup.func1(0xc4202da900, 0xc42011f340, 0x1, 0x7)
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/create_ig.go:87 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202da900, 0xc42011f2d0, 0x7, 0x7, 0xc4202da900, 0xc42011f2d0)
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x234
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5930a00, 0x3507900, 0x0, 0x0)
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x5930a00, 0x5964c58, 0x0)
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/root.go:95 +0x91
main.main()
    /private/tmp/kops-20180212-99778-1fmj9dk/kops-1.8.1/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
```

6. What did you expect to happen?

I expected the instance group to be created.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

**Comment by peterkuiper** [comment]
I'm proposing a doc update explaining this a little bit better:

* `kops edit cluster <clustername>`

Add the missing subnet under `subnets:`, ie:

```
  - cidr: 172.20.64.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
```

* Preview: `kops update cluster <clustername>`

* Apply: kops update cluster <clustername> --yes

* `kops create ig morenodes --subnet us-east-1a`

or, in case you need it to be in more than one subnet, use a comma-separated list:

* kops create ig morenodes --subnet us-east-1a,us-east-1b,us-east-1c

* Preview: `kops update cluster <clustername>`

* Apply: kops update cluster <clustername> --yes

**Comment by chrislovecnm** [comment]
I like it ... You can also mention kops replace command with a manifest.  You can add the new ig and subnets without edit commands.

**Comment by peterkuiper** [comment]
What would that look like? Something like this, or maybe I misunderstood?

===
`kops get cluster $NAME -o yaml > $NAME.yaml`

Edit $NAME.yaml and add the required subnet(s) under `subnets`:

`kops replace -f $NAME.yaml`
===

**Comment by makzee** [comment]
> I like it ... You can also mention kops replace command with a manifest. You can add the new ig and subnets without edit commands.

How to create new subnets without edit command ?

`kops create ig master-us-east-1a --subnet us-east-1a --role Master`

fails with `error assigning default machine type for masters: error finding default machine type: cannot find subnet "us-east-1a" (declared in instance group "master-us-east-1a", not found in cluster)`

Is `kops create ig` supposed to take care of creating ig as well as subnet ?
