### ISSUE TITLE
toolbox dump is throwing panic during e2e testing

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#4833]
kops is panicing during e2e testing

```
W0328 19:39:26.913] 2018/03/28 19:39:26 process.go:152: Step './hack/ginkgo-e2e.sh --ginkgo.flakeAttempts=2 --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort --report-dir=/workspace/_artifacts --disable-log-dump=true' finished in 12m40.003677372s
W0328 19:39:26.914] 2018/03/28 19:39:26 process.go:150: Running: /tmp/kops367845070/kops toolbox dump --name e2e-kops-aws-canary.test-cncf-aws.k8s.io -ojson
W0328 19:39:34.824] panic: interface conversion: interface {} is nil, not *ec2.Subnet
W0328 19:39:34.824] 
W0328 19:39:34.825] goroutine 1 [running]:
W0328 19:39:34.825] k8s.io/kops/pkg/resources/aws.DumpSubnet(0xc421230bc0, 0xc4212e8bb0, 0x0, 0x0)
W0328 19:39:34.825] 	/go/src/k8s.io/kops/pkg/resources/aws/subnet.go:33 +0x57c
W0328 19:39:34.826] k8s.io/kops/pkg/resources.BuildDump(0x4f64a00, 0xc42008a018, 0x7fa7564504e0, 0xc4212ba7d0, 0xc42082fef0, 0x0, 0xc42082fef0, 0x0)
W0328 19:39:34.826] 	/go/src/k8s.io/kops/pkg/resources/dump.go:58 +0x239
W0328 19:39:34.826] main.RunToolboxDump(0xc4200b81e0, 0x4f45a80, 0xc42008e008, 0xc4200b8620, 0x0, 0x0)
W0328 19:39:34.827] 	/go/src/k8s.io/kops/cmd/kops/toolbox_dump.go:116 +0x16b
W0328 19:39:34.827] main.NewCmdToolboxDump.func1(0xc42040f440, 0xc420beccc0, 0x0, 0x3)
W0328 19:39:34.827] 	/go/src/k8s.io/kops/cmd/kops/toolbox_dump.go:73 +0xe2
W0328 19:39:34.828] k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc42040f440, 0xc420becc30, 0x3, 0x3, 0xc42040f440, 0xc420becc30)
W0328 19:39:34.828] 	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x234
W0328 19:39:34.828] k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x51916e0, 0x51c6400, 0x0, 0x0)
W0328 19:39:34.829] 	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
W0328 19:39:34.829] k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x51916e0, 0x51c64e8, 0x0)
W0328 19:39:34.829] 	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
W0328 19:39:34.830] main.Execute()
W0328 19:39:34.830] 	/go/src/k8s.io/kops/cmd/kops/root.go:94 +0x91
W0328 19:39:34.830] main.main()
W0328 19:39:34.830] 	/go/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
W0328 19:39:34.835] 2018/03/28 19:39:34 process.go:152: Step '/tmp/kops367845070/kops toolbox dump --name e2e-kops-aws-canary.test-cncf-aws.k8s.io -ojson' finished in 8.019337203s
W0328 19:39:34.835] 2018/03/28 19:39:34 kops.go:574: error running kops toolbox dump: error during /tmp/kops367845070/kops toolbox dump --name e2e-kops-aws-canary.test-cncf-aws.k8s.io -ojson: exit status 2
```

See https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-canary/8016/build-log.txt

Same error in our regular e2e https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/4829/pull-kops-e2e-kubernetes-aws/5907/build-log.txt

**Comment by justinsb** [comment]
Believed fixed by #4848
