### ISSUE TITLE
`kops get instancegroups` does not work with existing s3 bucket

### ISSUE THREAD

**Issue by OleksandrBerezianskyi** [kubernetes/kops#548]
stacktrace:
```
 bin $ ./kops get instancegroups --name=${CLUSTER_NAME} --state=${KOPS_STATE_STORE}
W0930 11:20:26.599727   15405 registry.go:233] instancegroup was listed, but then not found "instancegroup"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x41e790]

goroutine 1 [running]:
panic(0x2050880, 0xc82000e0f0)
    /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.(*GetInstanceGroupsCmd).Run.func1(0x0, 0x0, 0x0)
    /home/ubuntu/work/sandbox/src/k8s.io/kops/cmd/kops/get_instancegroups.go:72 +0x20
reflect.Value.call(0x1b82920, 0x2996f18, 0x13, 0x242afa0, 0x4, 0xc8203797e0, 0x1, 0x1, 0x0, 0x0, ...)
    /usr/lib/go-1.6/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x1b82920, 0x2996f18, 0x13, 0xc8203797e0, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/lib/go-1.6/src/reflect/value.go:303 +0xb1
k8s.io/kops/util/pkg/tables.(*TableColumn).getFromValue(0xc82019ae70, 0x23e7da0, 0xc820605800, 0x196, 0x0, 0x0)
    /home/ubuntu/work/sandbox/src/k8s.io/kops/util/pkg/tables/format.go:27 +0xe9
k8s.io/kops/util/pkg/tables.(*Table).Render(0xc820629950, 0x1aeb020, 0xc8203797c0, 0x7fc8e38c9330, 0xc820024010, 0xc820629ae8, 0x6, 0x6, 0x0, 0x0)
    /home/ubuntu/work/sandbox/src/k8s.io/kops/util/pkg/tables/format.go:100 +0x486
main.(*GetInstanceGroupsCmd).Run(0x3654740, 0xc8202e09e0, 0x0, 0x2, 0x0, 0x0)
    /home/ubuntu/work/sandbox/src/k8s.io/kops/cmd/kops/get_instancegroups.go:89 +0x938
main.init.19.func1(0xc820484240, 0xc8202e09e0, 0x0, 0x2)
    /home/ubuntu/work/sandbox/src/k8s.io/kops/cmd/kops/get_instancegroups.go:26 +0x41
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc820484240, 0xc8202e0720, 0x2, 0x2, 0x0, 0x0)
    /home/ubuntu/work/sandbox/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x896
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x35e3e20, 0xc820484240, 0x0, 0x0)
    /home/ubuntu/work/sandbox/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x55c
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x35e3e20, 0x0, 0x0)
    /home/ubuntu/work/sandbox/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2d
main.Execute()
    /home/ubuntu/work/sandbox/src/k8s.io/kops/cmd/kops/root.go:40 +0xa2
main.main()
    /home/ubuntu/work/sandbox/src/k8s.io/kops/cmd/kops/main.go:9 +0x14
```

Creating an empty file `instancegroup`in s3 bucket under `instancegroup` folder seems to fix the issue

**Comment by justinsb** [comment]
I think this is similar to issue #520 

S3 doesn't really have folders, though some clients may create empty files that "pretend" to be files.  Are you using a particular client to interact with S3 that might do this?

I think we need to skip these "folders".  Can you let me know the metadata on the folder e.g. from `aws s3api  head-object --bucket ${BUCKET} --key {CLUSTER_NAME}/instancegroup` and then we can just skip them (or treat them as folders)

**Comment by OleksandrBerezianskyi** [comment]
@justinsb 
We have next files in ${KOPS_STATE_STORE}/instancegroups:
```
master-us-east-1a
master-us-east-1b
master-us-east-1d
nodes
```

When we run `./kops get instancegroups -v=8` it seems that kops is trying to read instancegroup with the name `instancegroup`:
```
$ ./kops get instancegroup -v 8
I0930 11:32:57.408911   15985 context.go:140] Found bucket "REDACTED_BUCKET" in region "us-east-1"
I0930 11:32:57.409039   15985 kubectl.go:65] Running command: kubectl config current-context
I0930 11:32:57.425148   15985 root.go:122] context = "REDACTED_CLUSTER_NAME"
I0930 11:32:57.425226   15985 kubectl.go:65] Running command: kubectl config view --minify --output json
I0930 11:32:57.440111   15985 kubectl.go:44] config = "{\n    \"kind\": \"Config\",\n    \"apiVersion\": \"v1\",\n    \"preferences\": {},\n    \"clusters\": [\n        {\n            \"name\": \"REDACTED_CLUSTER_NAME\",\n            \"cluster\": {\n                \"server\": \"https://api.internal.REDACTED_CLUSTER_NAME\",\n                \"certificate-authority-data\": \"REDACTED\"\n            }\n        }\n    ],\n    \"users\": [\n        {\n            \"name\": \"REDACTED_CLUSTER_NAME\",\n            \"user\": {\n                \"client-certificate-data\": \"REDACTED\",\n                \"client-key-data\": \"REDACTED\",\n                \"username\": \"admin\",\n                \"password\": \"REDACTED\"\n            }\n        }\n    ],\n    \"contexts\": [\n        {\n            \"name\": \"REDACTED_CLUSTER_NAME\",\n            \"context\": {\n                \"cluster\": \"REDACTED_CLUSTER_NAME\",\n                \"user\": \"REDACTED_CLUSTER_NAME\"\n            }\n        }\n    ],\n    \"current-context\": \"REDACTED_CLUSTER_NAME\"\n}"
Using cluster from kubectl context: REDACTED_CLUSTER_NAME

I0930 11:32:57.508431   15985 s3fs.go:174] Listed files in s3://REDACTED_BUCKET/REDACTED_CLUSTER_NAME/instancegroup: [s3://REDACTED_BUCKET/REDACTED_CLUSTER_NAME/instancegroup/ s3://REDACTED_BUCKET/REDACTED_CLUSTER_NAME/instancegroup/master-us-east-1a s3://REDACTED_BUCKET/REDACTED_CLUSTER_NAME/instancegroup/master-us-east-1b s3://REDACTED_BUCKET/REDACTED_CLUSTER_NAME/instancegroup/master-us-east-1d s3://REDACTED_BUCKET/REDACTED_CLUSTER_NAME/instancegroup/nodes]
I0930 11:32:57.670023   15985 s3fs.go:125] Reading file "s3://REDACTED_BUCKET/REDACTED_CLUSTER_NAME/instancegroup/instancegroup"
I0930 11:32:57.759676   15985 s3fs.go:125] Reading file "s3://REDACTED_BUCKET/REDACTED_CLUSTER_NAME/instancegroup/master-us-east-1a"
I0930 11:32:57.857577   15985 s3fs.go:125] Reading file "s3://REDACTED_BUCKET/REDACTED_CLUSTER_NAME/instancegroup/master-us-east-1b"
I0930 11:32:58.103011   15985 s3fs.go:125] Reading file "s3://REDACTED_BUCKET/REDACTED_CLUSTER_NAME/instancegroup/master-us-east-1d"
I0930 11:32:58.218208   15985 s3fs.go:125] Reading file "s3://REDACTED_BUCKET/REDACTED_CLUSTER_NAME/instancegroup/nodes"
NAME            ROLE    MACHINETYPE    MIN    MAX    ZONES
                        -    -
master-us-east-1a    Master    m4.large    1    1    us-east-1a
master-us-east-1b    Master    m4.large    1    1    us-east-1b
master-us-east-1d    Master    m4.large    1    1    us-east-1d
nodes            Node    m4.xlarge    2    2    us-east-1a,us-east-1b,us-east-1d,us-east-1e
```

**Comment by OleksandrBerezianskyi** [comment]
pasted incorrect description, will paste more info soon

**Comment by OleksandrBerezianskyi** [comment]
```
{
    "AcceptRanges": "bytes",
    "ContentType": "binary/octet-stream",
    "LastModified": "Fri, 23 Sep 2016 10:51:29 GMT",
    "ContentLength": 0,
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

**Comment by justinsb** [comment]
Thanks @OleksandrBerezianskyi .  I'll take a second look at the S3 listing logic.

Do you have any idea who is creating these empty files?  Are you mounting S3 using some sort of S3-filesystem tool?

**Comment by OleksandrBerezianskyi** [comment]
@justinsb no, the scenario is:

1. Generate the content of s3 bucket using kops
1. Download the content using cli `aws s3 cp`
1. Cleanup the bucket
1. Turn on server side encryption for the bucket
1. Upload the content using cli `aws s3 cp --sse REDACTED --sse-kms-key-id REDACTED`

**Comment by justinsb** [comment]
Just merged #549 which is a fix (I believe) @OleksandrBerezianskyi ... want to try it out and let me know?

**Comment by OleksandrBerezianskyi** [comment]
@justinsb works like a charm, thanks!

**Comment by justinsb** [comment]
Thanks for confirming @OleksandrBerezianskyi
