### ISSUE TITLE
Defaulted api-loadbalancer results in SIGSEGV/null pointer dereference with --api-ssl-certificate

### ISSUE THREAD

**Issue by tommij** [kubernetes/kops#5837]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0 (git-8b52ea6d1) / Version 1.10.0 (git-b1568cb09)

**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops create cluster --api-ssl-certificate=$ACM_CERTIFICATE_ARN --zones=us-west-2a --master-zones=us-west-2a --cloud=aws --ssh-access=1.1.1.1/32 --admin-access=1.1.1.1/32 --node-size=t2.micro --master-size=t2.micro --node-count=1 --ssh-public-key=/tmp/tmp.L6XKc8AkW5  --vpc=$EXISTING_VPC  --dry-run --output=yaml some.fqdn`

**5. What happened after the commands executed?**
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x296977a]

goroutine 1 [running]:
main.RunCreateCluster(0xc420d1ef80, 0x538b6a0, 0xc420092008, 0xc4208ce380, 0x0, 0x0)
	/go/src/k8s.io/kops/cmd/kops/create_cluster.go:1062 +0x2f8a
main.NewCmdCreateCluster.func1(0xc4202f3400, 0xc420c1e700, 0x1, 0xe)
	/go/src/k8s.io/kops/cmd/kops/create_cluster.go:256 +0x16a
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202f3400, 0xc420c1e620, 0xe, 0xe, 0xc4202f3400, 0xc420c1e620)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x55dc440, 0x2d38700, 0x0, 0x0)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:843 +0x334
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x55dc440, 0x5612040, 0x0)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.Execute()
	/go/src/k8s.io/kops/cmd/kops/root.go:96 +0x91
main.main()
	/go/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
```

**6. What did you expect to happen?**

A functional dry-run yaml output

**9. Anything else do we need to know?**

Seems to be caused by lack of defaulted load balancer type. If explicitly defined, all is well.
i.e:
supplying --api-loadbalancer-type=public|internal 

@Raffo - tagging you, as you seem to have added the feature/pr. thanks for that btw.

**Comment by Raffo** [comment]
Hi, I'm ACKing that and having a look later today/this week, many thanks for reporting!

**Comment by Raffo** [comment]
@tommij I created a PR #5971 , but I just want to give you an heads up that the command that you reported here contains no LoadBalancer and while kops should definitely not crash (hence the fix), it doesn't make so much sense to specify an ACM cert without having an ELB.
