### ISSUE TITLE
create: Panic in (*DryRunTarget).PrintReport

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kops#600]
From https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws-updown/500:

```
2016/10/05 11:14:58 e2e.go:671: Step 'kops get' finished in 404.830594ms
2016/10/05 11:14:58 e2e.go:669: Running: kops config
I1005 11:14:58.548223    1006 create_cluster.go:317] Inferred --cloud=aws from zone "us-west-2a"
I1005 11:14:58.548342    1006 cluster.go:362] Assigned CIDR 172.20.32.0/19 to zone us-west-2a
I1005 11:14:59.439370    1006 populate_cluster_spec.go:196] Defaulting DNS zone to: Z1TY3VHSR6DLWF
Previewing changes that will be made:

I1005 11:15:00.281232    1006 apply_cluster.go:120] Adding default kubelet release asset: https://storage.googleapis.com/kubernetes-release-dev/ci/v1.5.0-alpha.0.1937+617fa912645f95/bin/linux/amd64/kubelet
I1005 11:15:00.282298    1006 apply_cluster.go:526] Found hash "2dd37c854c152f758a3600423be6cce3e4ddee9b" for "https://storage.googleapis.com/kubernetes-release-dev/ci/v1.5.0-alpha.0.1937+617fa912645f95/bin/linux/amd64/kubelet"
I1005 11:15:00.282349    1006 apply_cluster.go:131] Adding default kubectl release asset: https://storage.googleapis.com/kubernetes-release-dev/ci/v1.5.0-alpha.0.1937+617fa912645f95/bin/linux/amd64/kubectl
I1005 11:15:00.283369 1006 apply_cluster.go:526] Found hash "2ccf02af58cb787b74c3e4eec6e1e04f8d180beb" for "https://storage.googleapis.com/kubernetes-release-dev/ci/v1.5.0-alpha.0.1937+617fa912645f95/bin/linux/amd64/kubectl"
I1005 11:15:00.283403 1006 apply_cluster.go:142] Adding default CNI asset: https://storage.googleapis.com/kubernetes-release/network-plugins/cni-8a936732094c0941e1543ef5d292a1f4fffa1ac5.tar.gz
W1005 11:15:00.283419 1006 apply_cluster.go:160] Using nodeup location from NODEUP_URL env var: "https://storage.googleapis.com/kops-ci/bin/git-5871b24/linux/amd64/nodeup"
I1005 11:15:00.520767 1006 executor.go:68] Tasks: 0 done / 47 total; 22 can run
I1005 11:15:02.084116    1006 executor.go:68] Tasks: 22 done / 47 total; 10 can run
I1005 11:15:02.338574    1006 executor.go:68] Tasks: 32 done / 47 total; 13 can run
I1005 11:15:02.848188    1006 executor.go:68] Tasks: 45 done / 47 total; 2 can run
I1005 11:15:02.922134    1006 executor.go:68] Tasks: 47 done / 47 total; 0 can run
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x4c93c9]

goroutine 1 [running]:
panic(0x203e540, 0xc820018130)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
k8s.io/kops/upup/pkg/fi.(*DryRunTarget).PrintReport(0xc8208d1d00, 0xc8202c3ef0, 0x7f980f631110, 0xc820034010, 0x0, 0x0)
        /go/src/k8s.io/kops/upup/pkg/fi/dryrun_target.go:76 +0x149
k8s.io/kops/upup/pkg/fi.(*DryRunTarget).Finish(0xc8208d1d00, 0xc8202c3ef0, 0x0, 0x0)
        /go/src/k8s.io/kops/upup/pkg/fi/dryrun_target.go:294 +0x54
k8s.io/kops/upup/pkg/fi/cloudup.(*ApplyClusterCmd).Run(0xc8205a0140, 0x0, 0x0)
        /go/src/k8s.io/kops/upup/pkg/fi/cloudup/apply_cluster.go:505 +0x483a
main.(*CreateClusterCmd).Run(0x3412280, 0xc82026e320, 0x0, 0xa, 0x0, 0x0)
        /go/src/k8s.io/kops/cmd/kops/create_cluster.go:408 +0x329d
main.init.2.func1(0xc8204da000, 0xc82026e320, 0x0, 0xa)
        /go/src/k8s.io/kops/cmd/kops/create_cluster.go:48 +0x41
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc8204da000, 0xc82018bea0, 0xa, 0xa, 0x0, 0x0)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x896
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3407540, 0xc8204da000, 0x0, 0x0)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x55c
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x3407540, 0x0, 0x0)
        /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2d
main.Execute()
        /go/src/k8s.io/kops/cmd/kops/root.go:40 +0xa2
main.main()
        /go/src/k8s.io/kops/cmd/kops/main.go:9 +0x14
2016/10/05 11:15:02 e2e.go:671: Step 'kops config' finished in 4.761868987s
2016/10/05 11:15:02 e2e.go:146: Saved XML output to /workspace/_artifacts/junit_runner.xml.
```

**Comment by justinsb** [comment]
I _think_ the problem here was #677.  Let's see if it persists...

**Comment by chrislovecnm** [comment]
Closing ... Please reopen as needed
