### ISSUE TITLE
 concurrent map iteration and map write in protokube gossip mesh (repeat of #6635 )

### ISSUE THREAD

**Issue by jacksontj** [kubernetes/kops#7134]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.** 1.12

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.** 1.10

**3. What cloud provider are you using?** AWS

On the master I see:

```
 docker[27563]: fatal error: concurrent map iteration and map write
 docker[27563]: goroutine 1080 [running]:
 docker[27563]: runtime.throw(0x3004b1a, 0x26)
 docker[27563]:         /usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc42240cbc0 sp=0xc42240cba0 pc=0x42bcf1
 docker[27563]: runtime.mapiternext(0xc42240ccb8)
 docker[27563]:         /usr/local/go/src/runtime/hashmap.go:747 +0x55c fp=0xc42240cc50 sp=0xc42240cbc0 pc=0x40a58c
 docker[27563]: runtime.mapiterinit(0x289d240, 0xc420537980, 0xc42240ccb8)
 docker[27563]:         /usr/local/go/src/runtime/hashmap.go:737 +0x1f1 fp=0xc42240cc78 sp=0xc42240cc50 pc=0x409f41
 docker[27563]: k8s.io/kops/protokube/pkg/gossip/mesh.(*KVState).Size(0xc42000e048, 0xc4210531a0)
 docker[27563]:         /go/src/k8s.io/kops/protokube/pkg/gossip/mesh/mesh.pb.go:197 +0x8d fp=0xc42240cd28 sp=0xc42240cc78 pc=0x23217fd
 docker[27563]: k8s.io/kops/protokube/pkg/gossip/mesh.(*KVState).Marshal(0xc42000e048, 0x32327a0, 0xc42000e048, 0x7f82f00336a8, 0xc42000e048, 0x22f2601)
 docker[27563]:         /go/src/k8s.io/kops/protokube/pkg/gossip/mesh/mesh.pb.go:85 +0x2f fp=0xc42240cd80 sp=0xc42240cd28 pc=0x2320ebf
 docker[27563]: k8s.io/kops/vendor/github.com/gogo/protobuf/proto.Marshal(0x32327a0, 0xc42000e048, 0xc426ec66c8, 0xc426ec6748, 0x289aae0, 0xc420b11a40, 0xc426ec66c0)
 docker[27563]:         /go/src/k8s.io/kops/vendor/github.com/gogo/protobuf/proto/encode.go:233 +0x115 fp=0xc42240cdc8 sp=0xc42240cd80 pc=0x98a0a5
 docker[27563]: k8s.io/kops/protokube/pkg/gossip/mesh.(*KVState).Encode(0xc42000e048, 0x3229340, 0xc42000e048, 0xc420ac8060)
 docker[27563]:         /go/src/k8s.io/kops/protokube/pkg/gossip/mesh/state.go:213 +0x3e fp=0xc42240ce48 sp=0xc42240cdc8 pc=0x232578e
 docker[27563]: k8s.io/kops/vendor/github.com/weaveworks/mesh.(*gossipSender).deliver(0xc420b461e0, 0xc420c96240, 0xc42240cef0, 0x0, 0x0)
 docker[27563]:         /go/src/k8s.io/kops/vendor/github.com/weaveworks/mesh/gossip.go:144 +0x148 fp=0xc42240ceb8 sp=0xc42240ce48 pc=0x22f25a8
 docker[27563]: k8s.io/kops/vendor/github.com/weaveworks/mesh.(*gossipSender).run(0xc420b461e0, 0xc420c96240, 0xc42171a780, 0xc42171a7e0)
 docker[27563]:         /go/src/k8s.io/kops/vendor/github.com/weaveworks/mesh/gossip.go:144 +0x148 fp=0xc42240ceb8 sp=0xc42240ce48 pc=0x22f25a8
 docker[27563]: k8s.io/kops/vendor/github.com/weaveworks/mesh.(*gossipSender).run(0xc420b461e0, 0xc420c96240, 0xc42171a780, 0xc42171a7e0)
 docker[27563]:         /go/src/k8s.io/kops/vendor/github.com/weaveworks/mesh/gossip.go:105 +0x1e2 fp=0xc42240cfc0 sp=0xc42240ceb8 pc=0x22f2412
 docker[27563]: runtime.goexit()
 docker[27563]:         /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42240cfc8 sp=0xc42240cfc0 pc=0x457b71
 docker[27563]: created by k8s.io/kops/vendor/github.com/weaveworks/mesh.newGossipSender
 docker[27563]:         /go/src/k8s.io/kops/vendor/github.com/weaveworks/mesh/gossip.go:94 +0x132
 docker[27563]: goroutine 1 [sleep]:
```

I initially reported this in #6635 which was supposedly fixed in 1.12. I have just finished upgrading 1.12 and and still able to reproduce this failure-- so the bug still exists. I'm unable to re-open #6635 so I'm creating this.

**Comment by jacksontj** [comment]
Bump, I'm continue to see this issue on my clusters :/

**Comment by rifelpet** [comment]
Based on the Encode function in the stacktrace:
https://github.com/kubernetes/kops/blob/3b0af771e88e236bab51bdc7390dd2c370b95ad3/protokube/pkg/gossip/mesh/state.go#L212-L218

I wonder if the fix is as simple as adding an RLock and RUnlock at the beginning of the function, like this:
https://github.com/kubernetes/kops/blob/3b0af771e88e236bab51bdc7390dd2c370b95ad3/protokube/pkg/gossip/mesh/state.go#L150-L152

**Comment by jacksontj** [comment]
it seems that the state just wasn't making a deep copy of the state. I have opened #7219 with a fix
