### ISSUE TITLE
 concurrent map iteration and map write in protokube gossip mesh (repeat of #6635 and #7134 )

### ISSUE THREAD

**Issue by jacksontj** [kubernetes/kops#7259]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.** 1.12

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.** 1.10

**3. What cloud provider are you using?** AWS

On the master I see:

```
 fatal error: concurrent map iteration and map write
 goroutine 837 [running]:
 runtime.throw(0x3004b3a, 0x26)
         /usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc4218f7bb0 sp=0xc4218f7b90 pc=0x42bcf1
 runtime.mapiternext(0xc4218f7cb8)
         /usr/local/go/src/runtime/hashmap.go:747 +0x55c fp=0xc4218f7c40 sp=0xc4218f7bb0 pc=0x40a58c
 k8s.io/kops/protokube/pkg/gossip/mesh.(*KVState).MarshalTo(0xc420cb4208, 0xc420d48000, 0x568, 0x568, 0x568, 0x568, 0x2d51fc0)
         /go/src/k8s.io/kops/protokube/pkg/gossip/mesh/mesh.pb.go:100 +0xc5 fp=0xc4218f7d28 sp=0xc4218f7c40 pc=0x2321345
 k8s.io/kops/protokube/pkg/gossip/mesh.(*KVState).Marshal(0xc420cb4208, 0x32327c0, 0xc420cb4208, 0x7fb8ec126060, 0xc420cb4208, 0x22f2901)
         /go/src/k8s.io/kops/protokube/pkg/gossip/mesh/mesh.pb.go:87 +0x7f fp=0xc4218f7d80 sp=0xc4218f7d28 pc=0x23211ff
 k8s.io/kops/vendor/github.com/gogo/protobuf/proto.Marshal(0x32327c0, 0xc420cb4208, 0xc42050e248, 0xc42050e2c8, 0x289ab00, 0xc4217af8c0, 0xc42050e240)
         /go/src/k8s.io/kops/vendor/github.com/gogo/protobuf/proto/encode.go:233 +0x115 fp=0xc4218f7dc8 sp=0xc4218f7d80 pc=0x98a0a5
 k8s.io/kops/protokube/pkg/gossip/mesh.(*KVState).Encode(0xc420cb4208, 0x3229360, 0xc420cb4208, 0xc420866000)
         /go/src/k8s.io/kops/protokube/pkg/gossip/mesh/state.go:215 +0x3e fp=0xc4218f7e48 sp=0xc4218f7dc8 pc=0x2325a8e
 k8s.io/kops/vendor/github.com/weaveworks/mesh.(*gossipSender).deliver(0xc420530d20, 0xc4212de000, 0xc4218f7ef0, 0x0, 0x0)
         /go/src/k8s.io/kops/vendor/github.com/weaveworks/mesh/gossip.go:144 +0x148 fp=0xc4218f7eb8 sp=0xc4218f7e48 pc=0x22f2898
 k8s.io/kops/vendor/github.com/weaveworks/mesh.(*gossipSender).run(0xc420530d20, 0xc4212de000, 0xc420a49320, 0xc420a49380)
         /go/src/k8s.io/kops/vendor/github.com/weaveworks/mesh/gossip.go:105 +0x1e2 fp=0xc4218f7fc0 sp=0xc4218f7eb8 pc=0x22f2702
 runtime.goexit()
         /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4218f7fc8 sp=0xc4218f7fc0 pc=0x457b71
 created by k8s.io/kops/vendor/github.com/weaveworks/mesh.newGossipSender
         /go/src/k8s.io/kops/vendor/github.com/weaveworks/mesh/gossip.go:94 +0x132

```

After applying the update from #7134 we seem to have again reduced the frequency, but something is still writing and reading from the same map. Unfortunately the panic is not as helpful here -- so I might need some help from someone with more experience with this mesh stuff.

**Comment by jacksontj** [comment]
I haven't seen this after swapping to the memberlist gossip, this may still be an issue for the mesh gossip implementation but as I'm no longer using it (and it has severe scaling issues) I'm not going to be tracking this issue anymore.
