### ISSUE TITLE
Fail to install instances on OpenStack

### ISSUE THREAD

**Issue by czunker** [kubernetes/kops#7775]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.14.0 (git-d5078612f)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Not yet installed. Should be 1.14.6

**3. What cloud provider are you using?**
OpenStack (Version Rocky)

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops update cluster --name cz-playground.k8s.local --yes

**5. What happened after the commands executed?**
During execution:
W1011 18:11:33.583410    3069 executor.go:130] error running task "Instance/bastions-1-cz-playground-k8s-local" (9m44s remaining to succeed): Error creating instance: error creating server {{{bastions-1-cz-playground-k8s-local  ubuntucore16  t1-1-1 [] [] 170 [{ 5aafd70b-bcc9-47ab-b44f-efe9d3338427 }] map[KopsInstanceGroup:bastions cluster_generation:0 ig_generation:0 k8s:cz-playground.k8s.local] [] <nil>    0xc0011eb810 []} kubernetes-cz-playground-k8s-local-9d_bb_80_d2_27_dd_90_55_40_c5_8e_90_77_ac_df_af} 0xc000940c00}: Internal Server Error
W1011 18:11:33.583447    3069 executor.go:130] error running task "Instance/nodes-2-cz-playground-k8s-local" (9m44s remaining to succeed): Error creating instance: error creating server {{{nodes-2-cz-playground-k8s-local  36ae334f-7acf-4099-a944-fd8e713129e5  c1-4-8 [] [35 33 47 98 105 110 47 98 97 115 104 10 35 32 67 111 112 121 114 105 103 104 116 32 50 48 49 54 32 84 104 10
...
97 114 46 103 122 10 10 95 95 69 79 70 95 75 85 66 69 95 69 78 86 10 10 100 111 119 110 108 111 97 100 45 114 101 108 101 97 115 101 10 101 99 104 111 32 34 61 61 32 110 111 100 101 117 112 32 110 111 100 101 32 99 111 110 102 105 103 32 100 111 110 101 32 61 61 34 10] 171 [{ 0b792d0c-7fe5-41a4-b5e4-ad5988228c05 }] map[KopsInstanceGroup:nodes KubernetesCluster:cz-playground.k8s.local cluster_generation:0 ig_generation:1 k8s:cz-playground.k8s.local] [] <nil>    0xc0011eb810 []} kubernetes-cz-playground-k8s-local-9d_bb_80_d2_27_dd_90_55_40_c5_8e_90_77_ac_df_af} 0xc000b40c00}: Internal Server Error

**6. What did you expect to happen?**
The instances get created.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
$ kops get --name cz-playground.k8s.local -o yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-10-11T16:03:57Z
  name: cz-playground.k8s.local
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v2
        ignore-volume-az: true
      loadbalancer:
        floatingNetwork: internet
        floatingNetworkID: 80ed5376-70ad-4c94-ba22-7c2af071edc8
        method: ROUND_ROBIN
        provider: octavia
        useOctavia: true
      monitor:
        delay: 1m
        maxRetries: 3
        timeout: 30s
      router:
        externalNetwork: internet
  cloudProvider: openstack
  configBase: swift://kops-openstack-playground-cz/cz-playground.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-170-1
      name: 0-1
      volumeType: volumes_hdd
    - instanceGroup: master-171-1
      name: 1-1
      volumeType: volumes_hdd
    - instanceGroup: master-170-2
      name: 0-2
      volumeType: volumes_hdd
    memoryRequest: 100Mi
    name: main
    version: 3.2.24
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-170-1
      name: 0-1
      volumeType: volumes_hdd
    - instanceGroup: master-171-1
      name: 1-1
      volumeType: volumes_hdd
    - instanceGroup: master-170-2
      name: 0-2
      volumeType: volumes_hdd
    memoryRequest: 100Mi
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.14.6
  masterPublicName: api.cz-playground.k8s.local
  networkCIDR: 10.0.0.0/20
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.2.0/23
    name: "170"
    type: Private
    zone: "170"
  - cidr: 10.0.4.0/23
    name: "171"
    type: Private
    zone: "171"
  - cidr: 10.0.0.0/26
    name: utility-170
    type: Utility
    zone: "170"
  - cidr: 10.0.0.64/26
    name: utility-171
    type: Utility
    zone: "171"
  topology:
    bastion:
      bastionPublicName: bastion.cz-playground.k8s.local
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-10-11T16:04:01Z
  labels:
    kops.k8s.io/cluster: cz-playground.k8s.local
  name: bastions
spec:
  image: ubuntucore16
  machineType: t1-1-1
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-170
  - utility-171

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-10-11T16:03:58Z
  generation: 1
  labels:
    kops.k8s.io/cluster: cz-playground.k8s.local
  name: master-170-1
spec:
  image: 36ae334f-7acf-4099-a944-fd8e713129e5
  machineType: c1-2-4
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-170-1
  role: Master
  subnets:
  - "170"

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-10-11T16:04:00Z
  generation: 1
  labels:
    kops.k8s.io/cluster: cz-playground.k8s.local
  name: master-170-2
spec:
  image: 36ae334f-7acf-4099-a944-fd8e713129e5
  machineType: c1-2-4
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-170-2
  role: Master
  subnets:
  - "170"

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-10-11T16:03:59Z
  generation: 1
  labels:
    kops.k8s.io/cluster: cz-playground.k8s.local
  name: master-171-1
spec:
  image: 36ae334f-7acf-4099-a944-fd8e713129e5
  machineType: c1-2-4
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-171-1
  role: Master
  subnets:
  - "171"

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-10-11T16:04:00Z
  generation: 1
  labels:
    kops.k8s.io/cluster: cz-playground.k8s.local
  name: nodes
spec:
  image: 36ae334f-7acf-4099-a944-fd8e713129e5
  machineType: c1-4-8
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - "170"
  - "171"

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
https://gist.github.com/czunker/a42dd6601ccb6dc25c46f830e85ca730

**9. Anything else do we need to know?**
This is the error message from nova API:
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi [req-999b754b-5fb2-42d5-a7f4-b20a3a2e2f9d 7304c7bddd624e928efc7984ff4585cf 56ae9e366c89413686645240e5886ee2 - default default] Unexpected exception in API method: ValueError: No JSON object could be decoded
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi Traceback (most recent call last):
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi   File "/openstack/venvs/nova-18.1.0/lib/python2.7/site-packages/nova/api/openstack/wsgi.py", line 801, in wrapped
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi     return f(*args, **kwargs)
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi   File "/openstack/venvs/nova-18.1.0/lib/python2.7/site-packages/nova/api/openstack/compute/images.py", line 148, in detail
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi     **page_params)
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi   File "/openstack/venvs/nova-18.1.0/lib/python2.7/site-packages/nova/image/api.py", line 80, in get_all
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi     return session.detail(context, **kwargs)
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi   File "/openstack/venvs/nova-18.1.0/lib/python2.7/site-packages/nova/image/glance.py", line 284, in detail
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi     _images.append(_translate_from_glance(image))
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi   File "/openstack/venvs/nova-18.1.0/lib/python2.7/site-packages/nova/image/glance.py", line 756, in _translate_from_glance
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi     image_meta = _convert_from_string(image_meta)
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi   File "/openstack/venvs/nova-18.1.0/lib/python2.7/site-packages/nova/image/glance.py", line 796, in _convert_from_string
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi     return _convert(_json_loads, metadata)
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi   File "/openstack/venvs/nova-18.1.0/lib/python2.7/site-packages/nova/image/glance.py", line 790, in _convert
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi     method(properties, attr)
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi   File "/openstack/venvs/nova-18.1.0/lib/python2.7/site-packages/nova/image/glance.py", line 772, in _json_loads
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi     properties[attr] = jsonutils.loads(prop)
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi   File "/openstack/venvs/nova-18.1.0/lib/python2.7/site-packages/oslo_serialization/jsonutils.py", line 264, in loads
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi     return json.loads(encodeutils.safe_decode(s, encoding), **kwargs)
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi     return _default_decoder.decode(s)
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi     raise ValueError("No JSON object could be decoded")
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi ValueError: No JSON object could be decoded
2019-10-11 15:11:29.239 8449 ERROR nova.api.openstack.wsgi 
2019-10-11 15:11:29.241 8449 INFO nova.api.openstack.wsgi [req-999b754b-5fb2-42d5-a7f4-b20a3a2e2f9d 7304c7bddd624e928efc7984ff4585cf 56ae9e366c89413686645240e5886ee2 - default default] HTTP exception thrown: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
<type 'exceptions.ValueError'>

**Comment by zetaab** [comment]
quite difficult to believe that the problem is in kops side. The error is coming from this row https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/openstack/instance.go#L52 and that is calling gophercloud library. From python stacktrace I can see that it contains lot of glance stuff. Is your image name containing some weird chars?

**Comment by zetaab** [comment]
@czunker can you remove that gist, it contains bytes debug information which can be decoded to string and it contains your password

**Comment by czunker** [comment]
@zetaab Thanks for the hint.

And yes the error accurs inside nova when it tries to contact glance.
I tried different images and different image names. The uuid was just another try.
I even used plain names like ubuntucore16. So no special charactes or something alike.
