### ISSUE TITLE
Help with Kops API (Please please please) 

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#881]
So I am trying to make the kops API example great again..

From the master branch run the following command :

```
make examples && KOPS_STATE_STORE=s3://kops-devel kops-api-example -name api1.example.com -zones us-east-1c
```

The code returns

```
error from up: error writing instancegroup: error marshalling object: error encoding object: no kind is registered for the type kops.InstanceGroup
```

I was able to pull a full stack trace from the `kubernetes.runtime` package that was the origin of the error

```
Queen-Of-Production-2:kops kris$ rm -rf kops_devel* && make examples && kops-api-example -name api1.example.com -zones us-east-1c
go install k8s.io/kops/examples/kops-api-example/...
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/debug/stack.go:16 +0x18
k8s.io/kops/vendor/k8s.io/kubernetes/pkg/runtime.(*notRegisteredErr).Error(0xc82041aa80, 0x0, 0x0)
	/go/src/k8s.io/kops/vendor/k8s.io/kubernetes/pkg/runtime/error.go:39 +0x4f
fmt.(*pp).handleMethods(0xc8204560d0, 0xc800000076, 0x0, 0x1)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:724 +0x4c2
fmt.(*pp).printArg(0xc8204560d0, 0x1cfb9e0, 0xc82041aa80, 0x76, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:806 +0x4a9
fmt.(*pp).doPrintf(0xc8204560d0, 0x2389a60, 0x19, 0xc82067d608, 0x1, 0x1)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:1238 +0x1dcd
fmt.Sprintf(0x2389a60, 0x19, 0xc82067d608, 0x1, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:203 +0x6f
fmt.Errorf(0x2389a60, 0x19, 0xc82067d608, 0x1, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:212 +0x65
k8s.io/kops/pkg/client/simple/vfsclientset.(*commonVFS).serialize(0xc820784cc0, 0x53c5328, 0xc8202cad00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kops/pkg/client/simple/vfsclientset/commonvfs.go:98 +0x1c0
k8s.io/kops/pkg/client/simple/vfsclientset.(*commonVFS).writeConfig(0xc820784cc0, 0x396d1c8, 0xc8207caae0, 0x53c5328, 0xc8202cad00, 0xc82067d7f0, 0x1, 0x1, 0x0, 0x0)
	/go/src/k8s.io/kops/pkg/client/simple/vfsclientset/commonvfs.go:107 +0x5f
k8s.io/kops/pkg/client/simple/vfsclientset.(*commonVFS).create(0xc820784cc0, 0x53c52f8, 0xc8202cad00, 0x0, 0x0)
	/go/src/k8s.io/kops/pkg/client/simple/vfsclientset/commonvfs.go:80 +0x399
k8s.io/kops/pkg/client/simple/vfsclientset.(*InstanceGroupVFS).Create(0xc820784cc0, 0xc8202cad00, 0x10, 0x0, 0x0)
	/go/src/k8s.io/kops/pkg/client/simple/vfsclientset/instancegroup.go:68 +0x69
main.up(0x0, 0x0)
	/go/src/k8s.io/kops/examples/kops-api-example/up.go:82 +0x9ba
main.main()
	/go/src/k8s.io/kops/examples/kops-api-example/main.go:54 +0x177
error from up: error writing instancegroup: error marshalling object: error encoding object: no kind is registered for the type kops.InstanceGroup
```

**Comment by chrislovecnm** [comment]
@justinsb promised to look at this tomorrow.  Thanks amigo!
