### ISSUE TITLE
new kubernetes 1.18

### ISSUE THREAD

**Issue by dmbarsukov** [kubernetes/kops#8891]
**1. kops version
Version 1.16.0 (git-4b0e62b82)

**2. kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**3. AWS cloud provider

**4. make simple cluster with new kubernetes version
kops create cluster --name=clustername  --zones=us-east-1a \
  --topology public \
  --node-count=1 --node-size=t3.medium --master-size=t3a.small  \
  --kubernetes-version=1.18.0

then get autoscaler addon
https://github.com/kubernetes/kops/blob/master/addons/cluster-autoscaler/cluster-autoscaler.sh

**5. What happened after the commands executed?**
the first error i've got
error: unable to recognize "cluster-autoscaler.yml": no matches for kind "Deployment" in version "extensions/v1beta1"

if you fix this with **sed -i -e "s@extensions/v1beta1@apps/v1@g" "${addon}"**

then the pod create successfully but don't starts.
when i explored pod logs i'v got this
```
I0410 06:12:09.912223       1 flags.go:52] FLAG: --address=":8085"
I0410 06:12:09.912831       1 flags.go:52] FLAG: --alsologtostderr="false"
I0410 06:12:09.912941       1 flags.go:52] FLAG: --application-metrics-count-limit="100"
I0410 06:12:09.913049       1 flags.go:52] FLAG: --azure-container-registry-config=""
I0410 06:12:09.913134       1 flags.go:52] FLAG: --balance-similar-node-groups="false"
I0410 06:12:09.913207       1 flags.go:52] FLAG: --boot-id-file="/proc/sys/kernel/random/boot_id"
I0410 06:12:09.913289       1 flags.go:52] FLAG: --cloud-config=""
I0410 06:12:09.913358       1 flags.go:52] FLAG: --cloud-provider="aws"
I0410 06:12:09.913458       1 flags.go:52] FLAG: --cloud-provider-gce-lb-src-cidrs="130.211.0.0/22,35.191.0.0/16,209.85.152.0/22,209.85.204.0/22"
I0410 06:12:09.913537       1 flags.go:52] FLAG: --cluster-name=""
I0410 06:12:09.913619       1 flags.go:52] FLAG: --configmap=""
I0410 06:12:09.913689       1 flags.go:52] FLAG: --container-hints="/etc/cadvisor/container_hints.json"
I0410 06:12:09.913788       1 flags.go:52] FLAG: --containerd="unix:///var/run/containerd.sock"
I0410 06:12:09.913871       1 flags.go:52] FLAG: --cores-total="0:320000"
I0410 06:12:09.913951       1 flags.go:52] FLAG: --docker="unix:///var/run/docker.sock"
I0410 06:12:09.914021       1 flags.go:52] FLAG: --docker-env-metadata-whitelist=""
I0410 06:12:09.914096       1 flags.go:52] FLAG: --docker-only="false"
I0410 06:12:09.914177       1 flags.go:52] FLAG: --docker-root="/var/lib/docker"
I0410 06:12:09.914262       1 flags.go:52] FLAG: --docker-tls="false"
I0410 06:12:09.914332       1 flags.go:52] FLAG: --docker-tls-ca="ca.pem"
I0410 06:12:09.914410       1 flags.go:52] FLAG: --docker-tls-cert="cert.pem"
I0410 06:12:09.914479       1 flags.go:52] FLAG: --docker-tls-key="key.pem"
I0410 06:12:09.914574       1 flags.go:52] FLAG: --enable-load-reader="false"
I0410 06:12:09.914645       1 flags.go:52] FLAG: --estimator="binpacking"
I0410 06:12:09.914723       1 flags.go:52] FLAG: --event-storage-age-limit="default=0"
I0410 06:12:09.914790       1 flags.go:52] FLAG: --event-storage-event-limit="default=0"
I0410 06:12:09.914884       1 flags.go:52] FLAG: --expander="random"
I0410 06:12:09.914979       1 flags.go:52] FLAG: --expendable-pods-priority-cutoff="0"
I0410 06:12:09.915083       1 flags.go:52] FLAG: --gke-api-endpoint=""
I0410 06:12:09.915160       1 flags.go:52] FLAG: --global-housekeeping-interval="1m0s"
I0410 06:12:09.915246       1 flags.go:52] FLAG: --google-json-key=""
I0410 06:12:09.915323       1 flags.go:52] FLAG: --housekeeping-interval="10s"
I0410 06:12:09.915393       1 flags.go:52] FLAG: --httptest.serve=""
I0410 06:12:09.915469       1 flags.go:52] FLAG: --kubeconfig=""
I0410 06:12:09.915549       1 flags.go:52] FLAG: --kubernetes=""
I0410 06:12:09.915631       1 flags.go:52] FLAG: --leader-elect="true"
I0410 06:12:09.915707       1 flags.go:52] FLAG: --leader-elect-lease-duration="15s"
I0410 06:12:09.915810       1 flags.go:52] FLAG: --leader-elect-renew-deadline="10s"
I0410 06:12:09.915907       1 flags.go:52] FLAG: --leader-elect-resource-lock="endpoints"
I0410 06:12:09.916030       1 flags.go:52] FLAG: --leader-elect-retry-period="2s"
I0410 06:12:09.916104       1 flags.go:52] FLAG: --log-backtrace-at=":0"
I0410 06:12:09.916187       1 flags.go:52] FLAG: --log-cadvisor-usage="false"
I0410 06:12:09.916257       1 flags.go:52] FLAG: --log-dir=""
I0410 06:12:09.916331       1 flags.go:52] FLAG: --logtostderr="false"
I0410 06:12:09.916412       1 flags.go:52] FLAG: --machine-id-file="/etc/machine-id,/var/lib/dbus/machine-id"
I0410 06:12:09.916490       1 flags.go:52] FLAG: --max-autoprovisioned-node-group-count="15"
I0410 06:12:09.916559       1 flags.go:52] FLAG: --max-empty-bulk-delete="10"
I0410 06:12:09.916656       1 flags.go:52] FLAG: --max-failing-time="15m0s"
I0410 06:12:09.916726       1 flags.go:52] FLAG: --max-graceful-termination-sec="600"
I0410 06:12:09.916803       1 flags.go:52] FLAG: --max-inactivity="10m0s"
I0410 06:12:09.916892       1 flags.go:52] FLAG: --max-node-provision-time="15m0s"
I0410 06:12:09.916972       1 flags.go:52] FLAG: --max-nodes-total="0"
I0410 06:12:09.917041       1 flags.go:52] FLAG: --max-total-unready-percentage="33"
I0410 06:12:09.917119       1 flags.go:52] FLAG: --memory-total="0:6400000"
I0410 06:12:09.917200       1 flags.go:52] FLAG: --min-replica-count="0"
I0410 06:12:09.917289       1 flags.go:52] FLAG: --namespace="kube-system"
I0410 06:12:09.917359       1 flags.go:52] FLAG: --node-autoprovisioning-enabled="false"
I0410 06:12:09.917437       1 flags.go:52] FLAG: --node-group-auto-discovery=""
I0410 06:12:09.917516       1 flags.go:52] FLAG: --nodes="[1:2:nodes.dev.sample.com]"
I0410 06:12:09.917607       1 flags.go:52] FLAG: --ok-total-unready-count="3"
I0410 06:12:09.917681       1 flags.go:52] FLAG: --scale-down-candidates-pool-min-count="50"
I0410 06:12:09.917759       1 flags.go:52] FLAG: --scale-down-candidates-pool-ratio="0.1"
I0410 06:12:09.917831       1 flags.go:52] FLAG: --scale-down-delay-after-add="10m0s"
I0410 06:12:09.917907       1 flags.go:52] FLAG: --scale-down-delay-after-delete="10s"
I0410 06:12:09.917989       1 flags.go:52] FLAG: --scale-down-delay-after-failure="3m0s"
I0410 06:12:09.918067       1 flags.go:52] FLAG: --scale-down-enabled="true"
I0410 06:12:09.918138       1 flags.go:52] FLAG: --scale-down-non-empty-candidates-count="30"
I0410 06:12:09.918212       1 flags.go:52] FLAG: --scale-down-unneeded-time="10m0s"
I0410 06:12:09.918293       1 flags.go:52] FLAG: --scale-down-unready-time="20m0s"
I0410 06:12:09.918589       1 flags.go:52] FLAG: --scale-down-utilization-threshold="0.5"
I0410 06:12:09.918670       1 flags.go:52] FLAG: --scan-interval="10s"
I0410 06:12:09.918755       1 flags.go:52] FLAG: --skip-nodes-with-local-storage="false"
I0410 06:12:09.918833       1 flags.go:52] FLAG: --skip-nodes-with-system-pods="true"
I0410 06:12:09.918928       1 flags.go:52] FLAG: --stderrthreshold="0"
I0410 06:12:09.919014       1 flags.go:52] FLAG: --storage-driver-buffer-duration="1m0s"
I0410 06:12:09.919105       1 flags.go:52] FLAG: --storage-driver-db="cadvisor"
I0410 06:12:09.919230       1 flags.go:52] FLAG: --storage-driver-host="localhost:8086"
I0410 06:12:09.919323       1 flags.go:52] FLAG: --storage-driver-password="root"
I0410 06:12:09.919403       1 flags.go:52] FLAG: --storage-driver-secure="false"
I0410 06:12:09.919477       1 flags.go:52] FLAG: --storage-driver-table="stats"
I0410 06:12:09.919555       1 flags.go:52] FLAG: --storage-driver-user="root"
I0410 06:12:09.919644       1 flags.go:52] FLAG: --test.bench=""
I0410 06:12:09.919719       1 flags.go:52] FLAG: --test.benchmem="false"
I0410 06:12:09.919791       1 flags.go:52] FLAG: --test.benchtime="1s"
I0410 06:12:09.919802       1 flags.go:52] FLAG: --test.blockprofile=""
I0410 06:12:09.919807       1 flags.go:52] FLAG: --test.blockprofilerate="1"
I0410 06:12:09.919812       1 flags.go:52] FLAG: --test.count="1"
I0410 06:12:09.919935       1 flags.go:52] FLAG: --test.coverprofile=""
I0410 06:12:09.919947       1 flags.go:52] FLAG: --test.cpu=""
I0410 06:12:09.919952       1 flags.go:52] FLAG: --test.cpuprofile=""
I0410 06:12:09.919956       1 flags.go:52] FLAG: --test.memprofile=""
I0410 06:12:09.919961       1 flags.go:52] FLAG: --test.memprofilerate="0"
I0410 06:12:09.919966       1 flags.go:52] FLAG: --test.mutexprofile=""
I0410 06:12:09.919971       1 flags.go:52] FLAG: --test.mutexprofilefraction="1"
I0410 06:12:09.919976       1 flags.go:52] FLAG: --test.outputdir=""
I0410 06:12:09.919981       1 flags.go:52] FLAG: --test.parallel="2"
I0410 06:12:09.919985       1 flags.go:52] FLAG: --test.run=""
I0410 06:12:09.919991       1 flags.go:52] FLAG: --test.short="false"
I0410 06:12:09.919998       1 flags.go:52] FLAG: --test.timeout="0s"
I0410 06:12:09.920003       1 flags.go:52] FLAG: --test.trace=""
I0410 06:12:09.920009       1 flags.go:52] FLAG: --test.v="false"
I0410 06:12:09.920014       1 flags.go:52] FLAG: --v="4"
I0410 06:12:09.920020       1 flags.go:52] FLAG: --version="false"
I0410 06:12:09.920032       1 flags.go:52] FLAG: --vmodule=""
I0410 06:12:09.920038       1 flags.go:52] FLAG: --write-status-configmap="true"
I0410 06:12:09.920054       1 main.go:287] Cluster Autoscaler 1.1.0
F0410 06:12:10.017882       1 main.go:319] Failed to get nodes from apiserver: v1.NodeList: Items: []v1.Node: v1.Node: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, parsing 1564 ...":{},"v:\"... at {"kind":"NodeList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/nodes","resourceVersion":"2414"},"items":[{"metadata":{"name":"ip-172-20-53-206.ec2.internal","selfLink":"/api/v1/nodes/ip-172-20-53-206.ec2.internal","uid":"036b77e7-9e1d-494d-a6b0-91d03283535b","resourceVersion":"1645","creationTimestamp":"2020-04-10T06:01:52Z","labels":{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/instance-type":"t3.medium","beta.kubernetes.io/os":"linux","failure-domain.beta.kubernetes.io/region":"us-east-1","failure-domain.beta.kubernetes.io/zone":"us-east-1a","kops.k8s.io/instancegroup":"nodes","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"ip-172-20-53-206.ec2.internal","kubernetes.io/os":"linux","kubernetes.io/role":"node","node-role.kubernetes.io/node":"","node.kubernetes.io/instance-type":"t3.medium","topology.kubernetes.io/region":"us-east-1","topology.kubernetes.io/zone":"us-east-1a"},"annotations":{"node.alpha.kubernetes.io/ttl":"0","volumes.kubernetes.io/controller-managed-attach-detach":"true"},"managedFields":[{"manager":"kops-controller","operation":"Update","apiVersion":"v1","time":"2020-04-10T06:01:52Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{"f:kops.k8s.io/instancegroup":{},"f:kubernetes.io/role":{},"f:node-role.kubernetes.io/node":{}}}}},{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2020-04-10T06:02:02Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:node.alpha.kubernetes.io/ttl":{}}},"f:spec":{"f:podCIDR":{},"f:podCIDRs":{".":{},"v:\"100.96.1.0/24\"":{}}},"f:status":{"f:conditions":{"k:{\"type\":\"NetworkUnavailable\"}":{".":{},"f:lastHeartbeatTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}}}}},{"manager":"kubelet","operation":"Update","apiVersion":"v1","time":"2020-04-10T06:07:43Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:volumes.kubernetes.io/controller-managed-attach-detach":{}},"f:labels":{".":{},"f:beta.kubernetes.io/arch":{},"f:beta.kubernetes.io/instance-type":{},"f:beta.kubernetes.io/os":{},"f:failure-domain.beta.kubernetes.io/region":{},"f:failure-domain.beta.kubernetes.io/zone":{},"f:kubernetes.io/arch":{},"f:kubernetes.io/hostname":{},"f:kubernetes.io/os":{},"f:node.kubernetes.io/instance-type":{},"f:topology.kubernetes.io/region":{},"f:topology.kubernetes.io/zone":{}}},"f:spec":{"f:providerID":{}},"f:status":{"f:addresses":{".":{},"k:{\"type\":\"ExternalDNS\"}":{".":{},"f:address":{},"f:type":{}},"k:{\"type\":\"ExternalIP\"}":{".":{},"f:address":{},"f:type":{}},"k:{\"type\":\"Hostname\"}":{".":{},"f:address":{},"f:type":{}},"k:{\"type\":\"InternalDNS\"}":{".":{},"f:address":{},"f:type":{}},"k:{\"type\":\"InternalIP\"}":{".":{},"f:address":{},"f:type":{}}},"f:allocatable":{".":{},"f:attachable-volumes-aws-ebs":{},"f:cpu":{},"f:ephemeral-storage":{},"f:hugepages-1Gi":{},"f:hugepages-2Mi":{},"f:memory":{},"f:pods":{}},"f:capacity":{".":{},"f:attachable-volumes-aws-ebs":{},"f:cpu":{},"f:ephemeral-storage":{},"f:hugepages-1Gi":{},"f:hugepages-2Mi":{},"f:memory":{},"f:pods":{}},"f:conditions":{".":{},"k:{\"type\":\"DiskPressure\"}":{".":{},"f:lastHeartbeatTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"MemoryPressure\"}":{".":{},"f:lastHeartbeatTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"PIDPressure\"}":{".":{},"f:lastHeartbeatTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Ready\"}":{".":{},"f:lastHeartbeatTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:daemonEndpoints":{"f:kubeletEndpoint":{"f:Port":{}}},"f:images":{},"f:nodeInfo":{"f:architecture":{},"f:bootID":{},"f:containerRuntimeVersion":{},"f:kernelVersion":{},"f:kubeProxyVersion":{},"f:kubeletVersion":{},"f:machineID":{},"f:operatingSystem":{},"f:osImage":{},"f:systemUUID":{}}}}}]},"spec":{"podCIDR":"100.96.1.0/24","podCIDRs":["100.96.1.0/24"],"providerID":"aws:///us-east-1a/i-045c3bc62eb64ed07"},"status":{"capacity":{"attachable-volumes-aws-ebs":"25","cpu":"2","ephemeral-storage":"125753328Ki","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"3989412Ki","pods":"110"},"allocatable":{"attachable-volumes-aws-ebs":"25","cpu":"2","ephemeral-storage":"115894266893","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"3887012Ki","pods":"110"},"conditions":[{"type":"NetworkUnavailable","status":"False","lastHeartbeatTime":"2020-04-10T06:02:02Z","lastTransitionTime":"2020-04-10T06:02:02Z","reason":"RouteCreated","message":"RouteController created a route"},{"type":"MemoryPressure","status":"False","lastHeartbeatTime":"2020-04-10T06:07:43Z","lastTransitionTime":"2020-04-10T06:01:32Z","reason":"KubeletHasSufficientMemory","message":"kubelet has sufficient memory available"},{"type":"DiskPressure","status":"False","lastHeartbeatTime":"2020-04-10T06:07:43Z","lastTransitionTime":"2020-04-10T06:01:32Z","reason":"KubeletHasNoDiskPressure","message":"kubelet has no disk pressure"},{"type":"PIDPressure","status":"False","lastHeartbeatTime":"2020-04-10T06:07:43Z","lastTransitionTime":"2020-04-10T06:01:32Z","reason":"KubeletHasSufficientPID","message":"kubelet has sufficient PID available"},{"type":"Ready","status":"True","lastHeartbeatTime":"2020-04-10T06:07:43Z","lastTransitionTime":"2020-04-10T06:01:52Z","reason":"KubeletReady","message":"kubelet is posting ready status"}],"addresses":[{"type":"InternalIP","address":"172.20.53.206"},{"type":"ExternalIP","address":"3.86.241.52"},{"type":"Hostname","address":"ip-172-20-53-206.ec2.internal"},{"type":"InternalDNS","address":"ip-172-20-53-206.ec2.internal"},{"type":"ExternalDNS","address":"ec2-3-86-241-52.compute-1.amazonaws.com"}],"daemonEndpoints":{"kubeletEndpoint":{"Port":10250}},"nodeInfo":{"machineID":"ec2f3fe80af9d7bad0effd61e0ea66f2","systemUUID":"EC2F3FE8-0AF9-D7BA-D0EF-FD61E0EA66F2","bootID":"08b054b2-38cf-4550-bfa1-4bdd39d74659","kernelVersion":"4.9.0-11-amd64","osImage":"Debian GNU/Linux 9 (stretch)","containerRuntimeVersion":"docker://19.3.4","kubeletVersion":"v1.18.0","kubeProxyVersion":"v1.18.0","operatingSystem":"linux","architecture":"amd64"},"images":[{"names":["protokube:1.16.0"],"sizeBytes":292710238},{"names":["k8s.gcr.io/kube-proxy@sha256:9e858386d52d0abaf936c1d10a763648ab7d85c8eb0af08a50a64238146e5571","k8s.gcr.io/kube-proxy:v1.18.0"],"sizeBytes":116534263},{"names":["k8s.gcr.io/k8s-dns-kube-dns-amd64@sha256:618a82fa66cf0c75e4753369a6999032372be7308866fc9afb381789b1e5ad52","k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13"],"sizeBytes":51157394},{"names":["k8s.gcr.io/cluster-proportional-autoscaler-amd64@sha256:12370202895b621a2ac28226292e4578598f13c1502aa4d3ee90fff4325d9275","k8s.gcr.io/cluster-proportional-autoscaler-amd64:1.4.0"],"sizeBytes":45853555},{"names":["k8s.gcr.io/k8s-dns-sidecar-amd64@sha256:cedc8fe2098dffc26d17f64061296b7aa54258a31513b6c52df271a98bb522b3","k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13"],"sizeBytes":42852039},{"names":["k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64@sha256:45df3e8e0c551bd0c79cdba48ae6677f817971dcbd1eeed7fd1f9a35118410e4","k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13"],"sizeBytes":41372492},{"names":["k8s.gcr.io/pause-amd64@sha256:163ac025575b775d1c0f9bf0bdd0f086883171eb475b5068e7defa4ca9e76516","k8s.gcr.io/pause-amd64:3.0"],"sizeBytes":746888}]}},{"metadata":{"name":"ip-172-20-54-199.ec2.internal","selfLink":"/api/v1/nodes/ip-172-20-54-199.ec2.internal","uid":"2ce986ce-3775-40d0-a97f-5c2faf3c5d2b","resourceVersion":"2364","creationTimestamp":"2020-04-10T06:00:19Z","labels":{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/instance-type":"t3a.small","beta.kubernetes.io/os":"linux","failure-domain.beta.kubernetes.io/region":"us-east-1","failure-domain.beta.kubernetes.io/zone":"us-east-1a","kops.k8s.io/instancegroup":"master-us-east-1a","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"ip-172-20-54-199.ec2.internal","kubernetes.io/os":"linux","kubernetes.io/role":"master","node-role.kubernetes.io/master":"","node.kubernetes.io/instance-type":"t3a.small","topology.kubernetes.io/region":"us-east-1","topology.kubernetes.io/zone":"us-east-1a"},"annotations":{"node.alpha.kubernetes.io/ttl":"0","volumes.kubernetes.io/controller-managed-attach-detach":"true"},"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2020-04-10T06:00:29Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:node.alpha.kubernetes.io/ttl":{}}},"f:spec":{"f:podCIDR":{},"f:podCIDRs":{".":{},"v:\"100.96.0.0/24\"":{}},"f:taints":{}},"f:status":{"f:conditions":{"k:{\"type\":\"NetworkUnavailable\"}":{".":{},"f:lastHeartbeatTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}}}}},{"manager":"protokube","operation":"Update","apiVersion":"v1","time":"2020-04-10T06:01:18Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{"f:node-role.kubernetes.io/master":{}}}}},{"manager":"kops-controller","operation":"Update","apiVersion":"v1","time":"2020-04-10T06:01:23Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{"f:kops.k8s.io/instancegroup":{},"f:kubernetes.io/role":{}}}}},{"manager":"kubelet","operation":"Update","apiVersion":"v1","time":"2020-04-10T06:11:53Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:volumes.kubernetes.io/controller-managed-attach-detach":{}},"f:labels":{".":{},"f:beta.kubernetes.io/arch":{},"f:beta.kubernetes.io/instance-type":{},"f:beta.kubernetes.io/os":{},"f:failure-domain.beta.kubernetes.io/region":{},"f:failure-domain.beta.kubernetes.io/zone":{},"f:kubernetes.io/arch":{},"f:kubernetes.io/hostname":{},"f:kubernetes.io/os":{},"f:node.kubernetes.io/instance-type":{},"f:topology.kubernetes.io/region":{},"f:topology.kubernetes.io/zone":{}}},"f:spec":{"f:providerID":{}},"f:status":{"f:addresses":{".":{},"k:{\"type\":\"ExternalDNS\"}":{".":{},"f:address":{},"f:type":{}},"k:{\"type\":\"ExternalIP\"}":{".":{},"f:address":{},"f:type":{}},"k:{\"type\":\"Hostname\"}":{".":{},"f:address":{},"f:type":{}},"k:{\"type\":\"InternalDNS\"}":{".":{},"f:address":{},"f:type":{}},"k:{\"type\":\"InternalIP\"}":{".":{},"f:address":{},"f:type":{}}},"f:allocatable":{".":{},"f:attachable-volumes-aws-ebs":{},"f:cpu":{},"f:ephemeral-storage":{},"f:hugepages-1Gi":{},"f:hugepages-2Mi":{},"f:memory":{},"f:pods":{}},"f:capacity":{".":{},"f:attachable-volumes-aws-ebs":{},"f:cpu":{},"f:ephemeral-storage":{},"f:hugepages-1Gi":{},"f:hugepages-2Mi":{},"f:memory":{},"f:pods":{}},"f:conditions":{".":{},"k:{\"type\":\"DiskPressure\"}":{".":{},"f:lastHeartbeatTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"MemoryPressure\"}":{".":{},"f:lastHeartbeatTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"PIDPressure\"}":{".":{},"f:lastHeartbeatTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Ready\"}":{".":{},"f:lastHeartbeatTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:daemonEndpoints":{"f:kubeletEndpoint":{"f:Port":{}}},"f:images":{},"f:nodeInfo":{"f:architecture":{},"f:bootID":{},"f:containerRuntimeVersion":{},"f:kernelVersion":{},"f:kubeProxyVersion":{},"f:kubeletVersion":{},"f:machineID":{},"f:operatingSystem":{},"f:osImage":{},"f:systemUUID":{}}}}}]},"spec":{"podCIDR":"100.96.0.0/24","podCIDRs":["100.96.0.0/24"],"providerID":"aws:///us-east-1a/i-09405dea829531cdf","taints":[{"key":"node-role.kubernetes.io/master","effect":"NoSchedule"}]},"status":{"capacity":{"attachable-volumes-aws-ebs":"25","cpu":"2","ephemeral-storage":"62843416Ki","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"2019664Ki","pods":"110"},"allocatable":{"attachable-volumes-aws-ebs":"25","cpu":"2","ephemeral-storage":"57916492090","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"1917264Ki","pods":"110"},"conditions":[{"type":"NetworkUnavailable","status":"False","lastHeartbeatTime":"2020-04-10T06:00:22Z","lastTransitionTime":"2020-04-10T06:00:22Z","reason":"RouteCreated","message":"RouteController created a route"},{"type":"MemoryPressure","status":"False","lastHeartbeatTime":"2020-04-10T06:11:53Z","lastTransitionTime":"2020-04-10T06:00:19Z","reason":"KubeletHasSufficientMemory","message":"kubelet has sufficient memory available"},{"type":"DiskPressure","status":"False","lastHeartbeatTime":"2020-04-10T06:11:53Z","lastTransitionTime":"2020-04-10T06:00:19Z","reason":"KubeletHasNoDiskPressure","message":"kubelet has no disk pressure"},{"type":"PIDPressure","status":"False","lastHeartbeatTime":"2020-04-10T06:11:53Z","lastTransitionTime":"2020-04-10T06:00:19Z","reason":"KubeletHasSufficientPID","message":"kubelet has sufficient PID available"},{"type":"Ready","status":"True","lastHeartbeatTime":"2020-04-10T06:11:53Z","lastTransitionTime":"2020-04-10T06:00:29Z","reason":"KubeletReady","message":"kubelet is posting ready status"}],"addresses":[{"type":"InternalIP","address":"172.20.54.199"},{"type":"ExternalIP","address":"34.203.249.37"},{"type":"Hostname","address":"ip-172-20-54-199.ec2.internal"},{"type":"InternalDNS","address":"ip-172-20-54-199.ec2.internal"},{"type":"ExternalDNS","address":"ec2-34-203-249-37.compute-1.amazonaws.com"}],"daemonEndpoints":{"kubeletEndpoint":{"Port":10250}},"nodeInfo":{"machineID":"ec2a0d39dcc365cf7a578a8f01dcc09c","systemUUID":"EC2A0D39-DCC3-65CF-7A57-8A8F01DCC09C","bootID":"ecae5fb5-42b4-441b-a486-a0e6aab55df5","kernelVersion":"4.9.0-11-amd64","osImage":"Debian GNU/Linux 9 (stretch)","containerRuntimeVersion":"docker://19.3.4","kubeletVersion":"v1.18.0","kubeProxyVersion":"v1.18.0","operatingSystem":"linux","architecture":"amd64"},"images":[{"names":["kopeio/etcd-manager@sha256:0beb4340f37e96563f404e0e653ac27c5dfb6b1a82af4aa5088369ca2f3f6210","kopeio/etcd-manager:3.0.20191025"],"sizeBytes":650424964},{"names":["protokube:1.16.0"],"sizeBytes":292710238},{"names":["k8s.gcr.io/cluster-autoscaler@sha256:1e1fc9acbda4bc97ae1927723554dc8e4d2a4308080bc14f82ee174b1bd19795","k8s.gcr.io/cluster-autoscaler:v1.1.0"],"sizeBytes":199396729},{"names":["k8s.gcr.io/kube-apiserver@sha256:fc4efb55c2a7d4e7b9a858c67e24f00e739df4ef5082500c2b60ea0903f18248","k8s.gcr.io/kube-apiserver:v1.18.0"],"sizeBytes":172964371},{"names":["k8s.gcr.io/kube-controller-manager@sha256:d926b172b8fc3568d8eab9736b2f79a1afefcb809d030dd4465cbb0d444ce293","k8s.gcr.io/kube-controller-manager:v1.18.0"],"sizeBytes":162368019},{"names":["kope/dns-controller@sha256:384beca99af919c22fa147d983e73bb95557c2cfc25a7652fcae4fce46ec7f0e","kope/dns-controller:1.16.0"],"sizeBytes":124216523},{"names":["k8s.gcr.io/kube-proxy@sha256:9e858386d52d0abaf936c1d10a763648ab7d85c8eb0af08a50a64238146e5571","k8s.gcr.io/kube-proxy:v1.18.0"],"sizeBytes":116534263},{"names":["k8s.gcr.io/kube-scheduler@sha256:33063bc856e99d12b9cb30aab1c1c755ecd458d5bd130270da7c51c70ca10cf6","k8s.gcr.io/kube-scheduler:v1.18.0"],"sizeBytes":95275539},{"names":["kope/kops-controller@sha256:1f3abd67bfbb2c50931ab35db7f0049b836cf1551a8d3a11c8a09e3f944ca380","kope/kops-controller:1.16.0"],"sizeBytes":79338702},{"names":["k8s.gcr.io/pause-amd64@sha256:163ac025575b775d1c0f9bf0bdd0f086883171eb475b5068e7defa4ca9e76516","k8s.gcr.io/pause-amd64:3.0"],"sizeBytes":746888}]}}]}
goroutine 1 [running]:
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.stacks(0xc4206c9c00, 0xc420cd0000, 0x3d2b, 0x3e2d)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.(*loggingT).output(0x5618fa0, 0xc400000003, 0xc4200ed290, 0x52e7316, 0x7, 0x13f, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:717 +0x348
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.(*loggingT).printf(0x5618fa0, 0x3, 0x37364ff, 0x26, 0xc4209b9e88, 0x1, 0x1)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.Fatalf(0x37364ff, 0x26, 0xc4209b9e88, 0x1, 0x1)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:319 +0x4c5

```
how do i fix this?

**Comment by olemarkus** [comment]
kops 1.16 only supports kubernetes up to version 1.16. So you should wait for kops 1.18 before using kubernetes 1.18
