### ISSUE TITLE
Modifying master EC2 instance type results in SIGSEGV

### ISSUE THREAD

**Issue by azell** [kubernetes/kops#960]
```
"$GOPATH/bin/kops" edit ig master-us-east-1b --v=0 --name="$NAME"
```

Changed the master instance type from `m3.large` to `t2.large` and exited.

```
I1120 23:02:04.294095   40875 cluster.go:414] Using kubernetes latest stable version: v1.4.6
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb5642]

goroutine 1 [running]:
panic(0x17c7260, 0xc4200140c0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
k8s.io/kops/pkg/apis/kops.(*Cluster).Validate(0xc42010d080, 0x1bab100, 0x0, 0x0)
	/Users/zellster/gopath/src/k8s.io/kops/pkg/apis/kops/validation.go:296 +0x642
k8s.io/kops/upup/pkg/fi/cloudup.(*populateClusterSpec).run(0xc4208679c0, 0xc42096b910, 0x0)
	/Users/zellster/gopath/src/k8s.io/kops/upup/pkg/fi/cloudup/populate_cluster_spec.go:87 +0x9c
k8s.io/kops/upup/pkg/fi/cloudup.PopulateClusterSpec(0xc42010d080, 0x0, 0x0, 0xc420068820)
	/Users/zellster/gopath/src/k8s.io/kops/upup/pkg/fi/cloudup/populate_cluster_spec.go:69 +0xdf
main.RunEditInstanceGroup(0xc420512ec0, 0xc420147b00, 0xc4203ad9b0, 0x1, 0x3, 0x276b760, 0xc420030010, 0x28698b8, 0x0, 0x0)
	/Users/zellster/gopath/src/k8s.io/kops/cmd/kops/edit_instancegroup.go:142 +0xa0b
main.NewCmdEditInstanceGroup.func1(0xc420147b00, 0xc4203ad9b0, 0x1, 0x3)
	/Users/zellster/gopath/src/k8s.io/kops/cmd/kops/edit_instancegroup.go:46 +0x77
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc420147b00, 0xc4203ad920, 0x3, 0x3, 0xc420147b00, 0xc4203ad920)
	/Users/zellster/gopath/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x283dee0, 0x16a4600, 0x0, 0x0)
	/Users/zellster/gopath/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x283dee0, 0x28698b8, 0x0)
	/Users/zellster/gopath/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
	/Users/zellster/gopath/src/k8s.io/kops/cmd/kops/root.go:70 +0xbc
main.main()
	/Users/zellster/gopath/src/k8s.io/kops/cmd/kops/main.go:31 +0x14
```

```
$ uname -a
Darwin Adams-MacBook-Pro.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
$ git log -n 1
commit 9e1b3dce55b08ddb8952d070a0720fbf420da71b
Merge: 77d42b3 4bea8f8
Author: Kris Childress <kris@nivenly.com>
Date:   Sun Nov 20 19:34:09 2016 -0700

    Merge pull request #750 from Shrugs/docs/runtime-config
    
    docs: add documentation for cluster.spec, namely runtimeConfig
```

**Comment by kris-nova** [comment]
Thanks for the issue @azell 

This issue is explained and fixed in this PR https://github.com/kubernetes/kops/pull/965
